[ALARM]
1=ALARME EIXO X - Anomalia acionamento do eixo X
2=ALARME EIXO Y - Anomalia acionamento do eixo Y
3=ALARME EIXO Z - Anomalia acionamento do eixo Z
4=ALARME EIXO B - Anomalia acionamento do eixo B
5=ALARME EIXO C - Anomalia acionamento do eixo C
6=ALARME EIXO W - Anomalia acionamento do eixo W
9=ALLARME GENERALE - Assenza alimentazione agli azionamenti degli assi
15=ALLARME SOFTWARE - Allarme lettura scrittura contatori
19=ALARME EIXO MORSA M10 - Anomalia acionamento eixo morsa M10
20=ALARME EIXO MORSA M11 - Anomalia acionamento eixo morsa M11
21=ALARME EIXO MORSA M12 - Anomalia acionamento eixo morsa M12
22=ALARME EIXO MORSA M13 - Anomalia acionamento eixo morsa M13
23=ALARME EIXO MORSA M14 - Anomalia acionamento eixo morsa M14
24=ALARME EIXO MORSA M15 - Anomalia acionamento eixo morsa M15
32=ALARME GERAL - Alimentações não presentes
33=ALARME GERAL - Emergência pressionada
34=ALARME GERAL - Auxiliares não inseridos
35=ALARME GERAL - Pressão insuficiente de ar
36=ALARME GERAL - Temperatura irregular do armário
37=ALARME GERAL - Térmicos disparados
39=ALARME TRANSP. APARAS - Disparou o térmico do transportador
40=ALARME ASPIRADOR - Disparou o térmico do aspirador
42=ALARME GERAL - CNC em alarme
43=ALARME GERAL - CNC1 em alarme
44=ALARME GERAL - CNC2 em alarme
46=ALARME GERAL - Not all CNC0, CNC1, CNC2 in manual mode
47=ALARME GERAL - Not all CNC0, CNC1, CNC2 in automatic mode
48=ALARME MANDRIL - Anomalia inversor do mandril
49=ALARME MANDRIL - Inversor do mandril em sobrecarga
50=ALARME MANDRIL - Mandril não em rotação
51=ALARME MANDRIL - Velocidade não em regime
52=ALARME MANDRIL - Temporização desbloqueio da ferramenta
53=ALARME MANDRIL - Temporização bloqueio da ferramenta
54=ALARME MANDRIL - Disfunção F.C bloqueio da ferramenta
55=ALARME MANDRIL - Ferramenta não enganchada corretamente
56=ALARME MANDRIL - Ferramenta desconhecida no mandril
57=SPINDLE ALARM - Overload Relay Tripped Module Spindle Cooling
58=ALARME MANDRIL - Fluxóstato da centralina de arrefecimento do mandril em alarme
62=ALARME DE FUSO - Vibracoes excessivas no fuso
63=ALARME DO FUSO - Temperatura excessiva no fuso
64=ALARMES EIXOS - Eixo X em extra curso positivo
65=ALARMES EIXOS - Eixo X em extra curso negativo
66=ALARMES EIXOS - Eixo Y em extra curso positivo
67=ALARMES EIXOS - Eixo Y em extra curso negativo
68=ALARMES EIXOS - Eixo Z em extra curso positivo
69=ALARMES EIXOS - Eixo Z em extra curso negativo
70=ALARMES EIXOS - Eixo B em extra curso positivo
71=ALARMES EIXOS - Eixo B em extra curso negativo
72=ALARMES EIXOS - Eixo C em extra curso positivo
73=ALARMES EIXOS - Eixo C em extra curso negativo
74=ALARMES EIXOS - Eixo P em extra curso positivo
75=ALARMES EIXOS - Eixo P em extra curso negativo
76=ALARMES EIXOS - Eixo H em extra curso positivo
77=ALARMES EIXOS - Eixo H em extra curso negativo
78=ALARMES EIXOS - Eixo W em extra curso positivo
79=ALARMES EIXOS - Eixo W em extra curso negativo
80=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 1
81=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 1
82=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 2
83=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 2
84=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 3
85=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 3
86=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 4
87=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 4
88=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 5
89=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 5
90=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 6
91=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 6
92=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 7
93=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 7
94=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 8
95=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 8
96=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 9
97=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 9
98=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 10
99=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 10
100=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 11
101=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 11
102=ALARME TROCA DE FERRAMENTAS - Impossível depositar ferramenta 12
103=ALARME TROCA DE FERRAMENTAS - Impossível retirar ferramenta 12
104=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non disinserito
105=ALARME ARMAZÉM DE FERRAMENTAS - Ciclo iniciado com mandril em potencial colisao com o armazem
106=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non fuori ingombro
107=ALARME MORSAS - Alta pressão ativa sem comando
108=ALARMES EIXOS - Colisao potencial entre a ferramenta e os protetores dianteiros
115=ALARME MORSAS - Morsa 10 não em posicionamento correto
116=ALARME MORSAS - Morsa 11 não em posicionamento correto
117=ALARME MORSAS - Morsa 12 não em posicionamento correto
118=ALARME MORSAS - Morsa 13 não em posicionamento correto
119=ALARME MORSAS - Morsa 14 não em posicionamento correto
120=ALARME MORSAS - Morsa 15 não em posicionamento correto
124=ALARME MORSAS - Contagem errada das morsas
125=ALARME MORSAS - Erro pos. Morsas do computador: valores fora do limiar
136=ALARME MORSAS - Alimentatore morse motorizzate non OK
138=ALLARME BATTUTA DI PRECISIONE - Battuta non inserita
139=ALLARME BATTUTA DI PRECISIONE - Battuta non disinserita
140=ALLARME BATTUTA DI PRECISIONE - Errore posizione a riposo della battuta
141=ALLARME BATTUTA DI PRECISIONE - Errore indice di tastatura
142=ALLARME BATTUTA DI PRECISIONE - Pezzo non trovato
143=ALLARME DI POSIZIONAMENTO - Pezzo appoggiato male alla battuta di riferimento
154=ALLARME BATTUTE - Battuta DX4 non in posizione X4R
155=ALLARME BATTUTE - Disfunzione Finecorsa Battuta DX4
156=ALLARME BATTUTE - Battuta SX1 non in posizione X1L
157=ALLARME BATTUTE - Battuta DX4 non in posizione X3R
158=ALLARME BATTUTE - Battuta DX4 non in posizione X2R
159=ALLARME BATTUTE - Battuta DX4 non in posizione X1R
160=ALARME BATIDAS - Batida esq.1 não alta:
161=ALARME BATIDAS - Batida esq.1 não baixa:
166=ALARME BATIDAS - Batida dir.4 não alta:
167=ALARME BATIDAS - Batida dir.4 não baixa:
176=ALARME MESAS - Mesa não avante: controlar o sensor
177=ALARME MESAS - Mesa não avante: controlar a EV
178=ALARME MESAS - Mesa não atrás: controlar o sensor
179=ALARME MESAS - Mesa não atrás: controlar a EV
180=ALARME MESAS - Disfunção fim de curso mesa
198=ALARME LUBRICA - Nível baixo Lubrica normal
199=ALARME LUBRICA - Nível baixo Lubrica especial
200=ALARME APALPADOR MARPOSS - Apalpador ja no tope no inicio da apalpadela
201=ALARME APALPADOR MARPOSS - Peca nao detetada pelo apalpador
202=ALARME APALPADOR MARPOSS - Erro indice apalpador
203=ALARME APALPADOR MARPOSS - Apalpador Marposs em condicao de erro
204=ALARME APALPADOR MARPOSS - Bateria descarregada do apalpador Marposs
205=ALARME APALPADOR MARPOSS - Apalpador ainda no tope no fim da apalpadela
206=ALARME APALPADOR MARPOSS - Correction values too big: verify probe
212=ALARME LUBRIFICAÇÃO DAS GUIAS - Nível baixo de lubrificante
213=ALARME LUBRIFICAÇÃO DAS GUIAS - Anomalia bomba/eletroválvula
214=ALARME LUBRIFICAÇÃO DAS GUIAS - Ausência de execução por muitas horas de trabalho
215=ALARME LUBRIFICAÇÃO DAS GUIAS - Ausência comutação sensor na bombada individual 
224=ALARME SOFTWARE - Abertura\Fechamento do arquivo errado: Path_conf.txt
225=ALARME SOFTWARE - Abertura errada do arquivo: Config.par
226=ALARME SOFTWARE - Abertura errada do arquivo: Tools.txt
227=ALARME SOFTWARE - Abertura errada do arquivo: Heads.txt
228=ALARME SOFTWARE - Erro na chamada da ferramenta 
229=ALARME SOFTWARE - Fechamento errado do arquivo: Config.Par/Tools.txt/Heads.txt 
230=ALARME SOFTWARE - Erro de leitura do arquivo
231=ALARME SOFTWARE - Abertura errada do arquivo: Variable.txt
232=ALARME SOFTWARE - Fechamento errado do arquivo: Variable.txt
233=ALARME SOFTWARE - Alarme ausência de driver
234=ALARME SOFTWARE - Configuração errada da máquina 
235=ALARME SOFTWARE - Valor acima do limiar em controlos de rotina ISO CNC
236=ALARME SOFTWARE - Tabela utensilios não carregado (execucao M209)
237=ALARME SOFTWARE - Alarme movimento eixos X - Y - Z 
243=ALARME MORSAS - Morsa 10 não em posicionamento
244=ALARME MORSAS - Morsa 11 não em posicionamento
245=ALARME MORSAS - Morsa 12 não em posicionamento
246=ALARME MORSAS - Morsa 13 não em posicionamento
247=ALARME MORSAS - Morsa 14 não em posicionamento
248=ALARME MORSAS - Morsa 15 não em posicionamento
252=ALARME MORSAS - Micro morsa perdida durante o posicionamento
253=ALARME MORSAS - Micro morsa eixo X não encontrado em controlo de posição
256=ALLARME GENERALE - Errore caricamento ISOMG in memoria
257=ALLARME GENERALE - Timeout caricamento ISOMG in memoria
260=ALARME CAN OPEN - Comunicação CanOpen em anomalia
270=ALLARME RIPARI - Riparo laterale o tunnel SX non chiuso
271=ALLARME RIPARI - Riparo laterale o tunnel DX non chiuso
272=ALARME COBERTURAS - Temporização cobertura anterior não fechada: controlar o sensor
273=ALARME COBERTURAS - Temporização cobertura anterior não fechada: controlar a EV
274=ALARME COBERTURAS - Temporização cobertura anterior não aberta: controlar o sensor
275=ALARME COBERTURAS - Temporização cobertura anterior não aberta: controlar a EV
276=ALARME COBERTURAS - Disfunção fim de curso cobertura anterior
282=ALARME COBERTURAS - Cobertura posterior esq. não fechada
283=ALARME COBERTURAS - Cobertura posterior dir. não fechada
286=ALARME COBERTURAS - Centralina de segurança não ativa com cobertura fechada
298=ALLARME RIPARI - Bordo sensibile ripari intervenuto
320=ALARME EMPURRADOR DAS MORSAS - Empur. morsas do eixo X não inserido: controlar o sensor
321=ALARME EMPURRADOR DAS MORSAS - Empur. morsas do eixo X não inserido: controlar a EV
322=ALARME EMPURRADOR DAS MORSAS - Empur. morsas do eixo X não desinserido: controlar o sensor
323=ALARME EMPURRADOR DAS MORSAS - Empur. morsas do eixo X não desinserido: controlar a EV
324=ALARME EMPURRADOR DAS MORSAS - Disfunção do fim de curso empur. morsas eixo X
342=ALLARME RILEVAMENTO MORSE - Time out inserzione rilevamento morse
343=ALLARME RILEVAMENTO MORSE - Time out disinserzione rilevamento morse
371=ALLARME MORSE - Alta pressione non attiva su morsa 10
372=ALLARME MORSE - Alta pressione non attiva su morsa 11
373=ALLARME MORSE - Alta pressione non attiva su morsa 12
374=ALLARME MORSE - Alta pressione non attiva su morsa 13
375=ALLARME MORSE - Alta pressione non attiva su morsa 14
376=ALLARME MORSE - Alta pressione non attiva su morsa 15
384=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla il sensore
385=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla la EV
386=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla il sensore
387=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla la EV
388=ALLARME RIPARI - Disfunzione finecorsa visiera bassa
394=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla il sensore
395=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla la EV
396=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla il sensore
397=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla la EV
402=ALLARME UTENSILI - Utensile T1 rotto
403=ALLARME UTENSILI - Utensile T2 rotto
404=ALLARME UTENSILI - Utensile T3 rotto
405=ALLARME UTENSILI - Utensile T4 rotto
406=ALLARME UTENSILI - Utensile T5 rotto
407=ALLARME UTENSILI - Utensile T6 rotto
408=ALLARME UTENSILI - Utensile T7 rotto
409=ALLARME UTENSILI - Utensile T8 rotto
410=ALLARME UTENSILI - Utensile T9 rotto
411=ALLARME UTENSILI - Utensile T10 rotto
412=ALLARME UTENSILI - Utensile T11 rotto
413=ALLARME UTENSILI - Utensile T12 rotto
414=ALLARME UTENSILI - Drill not alive
416=ALLARME GANTRY - Morse non agganciate in gantry
417=ALLARME GANTRY - Morse non sganciate in gantry
418=VICES AXES ALARM - Vices axes positions not congruent (lost encoder positions)
419=ALARME TROCA DE FERRAMENTAS - Inconsistencia entre esta ferramenta teorica e sensor de presenca ferramenta
420=ALARME DE VERIFICACAO DE FERRAMENTA - Ferramenta quebrada
421=ALARME DE VERIFICACAO DA FERRAMENTA - O dispositivo de verificacao da integridade da ferramenta nao esta funcionando
438=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa positivo
439=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa negativo
440=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa positivo
441=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa negativo
442=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa positivo
443=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa negativo
444=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa positivo
445=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa negativo
446=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa positivo
447=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa negativo
448=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa positivo
449=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa negativo
475=ALLARME CONFIGURAZIONE - Errore inizializzazione variabili PLC
476=ALLARME CONFIGURAZIONE - Errore lettura confmac
477=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (MGPilot)
478=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (REM_CTRL)
480=ALLARME ASSE X - Livello Batteria encoder basso
481=ALLARME ASSE Y - Livello Batteria encoder basso
482=ALLARME ASSE Z - Livello Batteria encoder basso
483=ALLARME ASSE A - Livello Batteria encoder basso
484=ALLARME ASSE W - Livello Batteria encoder basso
487=ALLARME ASSE X - Livello Batteria encoder basso e posizione assoluta persa
488=ALLARME ASSE Y - Livello Batteria encoder basso e posizione assoluta persa
489=ALLARME ASSE Z - Livello Batteria encoder basso e posizione assoluta persa
490=ALLARME ASSE A - Livello Batteria encoder basso e posizione assoluta persa
491=ALLARME ASSE W - Livello Batteria encoder basso e posizione assoluta persa
496=ALLARME ASSE X - Overflow sui giri massimi del multiturn dell'encoder assoluto
497=ALLARME ASSE Y - Overflow sui giri massimi del multiturn dell'encoder assoluto
498=ALLARME ASSE Z - Overflow sui giri massimi del multiturn dell'encoder assoluto
499=ALLARME ASSE A - Overflow sui giri massimi del multiturn dell'encoder assoluto
500=ALLARME ASSE W - Overflow sui giri massimi del multiturn dell'encoder assoluto
503=ALLARME ASSE X - Posizione assoluta encoder non inizializzata
504=ALLARME ASSE Y - Posizione assoluta encoder non inizializzata
505=ALLARME ASSE Z - Posizione assoluta encoder non inizializzata
506=ALLARME ASSE A - Posizione assoluta encoder non inizializzata
507=ALLARME ASSE W - Posizione assoluta encoder non inizializzata
512=ALLARME ASSE X - Funzione di reset encoder assoluto non riuscita
513=ALLARME ASSE Y - Funzione di reset encoder assoluto non riuscita
514=ALLARME ASSE Z - Funzione di reset encoder assoluto non riuscita
515=ALLARME ASSE A - Funzione di reset encoder assoluto non riuscita
516=ALLARME ASSE W - Funzione di reset encoder assoluto non riuscita
519=ALLARME ASSE X - La tensione DC del circuito principale è più bassa del valore standard
520=ALLARME ASSE Y - La tensione DC del circuito principale è più bassa del valore standard
521=ALLARME ASSE Z - La tensione DC del circuito principale è più bassa del valore standard
522=ALLARME ASSE A - La tensione DC del circuito principale è più bassa del valore standard
523=ALLARME ASSE W - La tensione DC del circuito principale è più bassa del valore standard
528=ALLARME ASSE X - Mancanza di una fase in ingresso
529=ALLARME ASSE Y - Mancanza di una fase in ingresso
530=ALLARME ASSE Z - Mancanza di una fase in ingresso
531=ALLARME ASSE A - Mancanza di una fase in ingresso
532=ALLARME ASSE W - Mancanza di una fase in ingresso
535=ALLARME ASSE X - La velocità del motore è in overshoot rispetto al valore massimo di targa
536=ALLARME ASSE Y - La velocità del motore è in overshoot rispetto al valore massimo di targa
537=ALLARME ASSE Z - La velocità del motore è in overshoot rispetto al valore massimo di targa
538=ALLARME ASSE A - La velocità del motore è in overshoot rispetto al valore massimo di targa
539=ALLARME ASSE W - La velocità del motore è in overshoot rispetto al valore massimo di targa
544=ALLARME PLC IEC - PLC IEC timeout di not alive
545=ALLARME PLC IEC - Errore di comunicazione COM con inverter 0
560=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse X
561=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Y
562=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Z
563=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse A
564=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse W

[MSG]
1=MENSAGEM OPERADOR - Eixos não referidos
2=MENSAGEM OPERADOR - Máquina em HOLD
3=MENSAGEM OPERADOR - Ferramenta desconhecida no mandril
4=MENSAGEM OPERADOR - Potenciómetro em zero no Ciclo Automático
5=MENSAGEM OPERADOR - Máquina em HOLD do depósito
6=MENSAGEM OPERADOR - Máquina em HOLD de morsas área esq.
7=MENSAGEM OPERADOR - Máquina em HOLD de morsas área dir.
8=MENSAGEM OPERADOR - Máquina em HOLD do mandril
9=MENSAGEM OPERADOR - Máquina em HOLD de coberturas
10=MENSAGEM OPERADOR - Magazzino in potenziale collisione col carter laterale SX della macchina
11=MENSAGEM OPERADOR - Mandril em potencial colisao com o armazem de ferramentas
12=MENSAGEM OPERADOR - Bloco execuções FATM ativo
13=MENSAGEM OPERADOR - Hold apertura / chiusura ripari anteriori da posizione assi Y, B, C
14=MENSAGEM OPERADOR - Atenção: Possível curto-circuito nas entradas não retentivas
15=MESSAGGIO OPERATORE - Potenziale collisione fra utensile e riparo anteriore
16=MENSAGEM OPERADOR - Desbloqueio direto ferramenta somente com coberturas baixas
25=MENSAGEM OPERADOR - Lubrificação automática desabilitada
27=MENSAGEM OPERADOR - Assenza uscite pericolose con centralina di sicurezza ok
30=MENSAGEM OPERADOR - Inizializzazione password Bridge fatta, riavviare
31=MENSAGEM OPERADOR - Errore scrittura file contatori
77=MENSAGEM OPERADOR - Errore caricamento funzioni manuali (MGPilot)
78=MENSAGEM OPERADOR - Errore caricamento funzioni manuali (REM_CTRL)
80=MESSAGGIO OPERATORE - Motore asse X in preallarme da sovraccarico
81=MESSAGGIO OPERATORE - Motore asse Y in preallarme da sovraccarico
82=MESSAGGIO OPERATORE - Motore asse Z in preallarme da sovraccarico
83=MESSAGGIO OPERATORE - Motore asse A in preallarme da sovraccarico
84=MESSAGGIO OPERATORE - Motore asse W in preallarme da sovraccarico
88=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso e posizione assoluta persa
89=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso e posizione assoluta persa
90=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso e posizione assoluta persa
91=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso e posizione assoluta persa
92=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso e posizione assoluta persa
96=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso
97=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso
98=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso
99=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso
100=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso
104=MESSAGGIO OPERATORE - Posizione assoluta encoder asse X non inizializzata
105=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Y non inizializzata
106=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Z non inizializzata
107=MESSAGGIO OPERATORE - Posizione assoluta encoder asse A non inizializzata
108=MESSAGGIO OPERATORE - Posizione assoluta encoder asse W non inizializzata
112=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse X
113=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Y
114=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Z
115=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse A
116=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse W
