A           B ATIVAR 
A ABRIR     B FECHAR 
A JOG -      B JOG + 
A DEPOSITO B EXTRAC. 
A DESINS. B INSERIM. 
A ATRAS     B AVANTE 
A HORAR. B ANTIHORAR 
A FIM       B INICIO 
A BLOQUE. B DESBLOQ. 
A ESQ      B DIR 
