@ECHO OFF

REM COPIA DI PLCM.PLC SULLA MACCHINA CONNESSA VIA RETE  (in "X:\plc\plc\")

REM ///////////////////////////////////////////////////////////////////////////////////////////////

REM copia in MACCHINA:
rem copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreRelease\plcm.plc"   "X:\plc\plc\"
rem copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreRelease\plcm.plc"   "Y:\isac\lav\lav\_PLC\"


REM copia su chiave USB:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreRelease\plcm.plc"   "G:\_______XXX\"

REM PAUSE
