[ALARM]
1=X轴报警 - X轴驱动故障
2=Y轴报警 - Y轴驱动故障
3=Z轴报警 - Z轴驱动故障
4=B轴报警 - B轴驱动故障
5=C轴报警 - C轴驱动故障
6=W轴报警 - W轴驱动故障
9=GENERAL ALARM - No power to the axes drives
15=SOFTWARE ALARM - Alarm counter read writing
19=M10轴夹钳报警 - M10轴驱动故障
20=M11轴夹钳报警 - M11轴驱动故障
21=M12轴夹钳报警 - M12轴驱动故障
22=M13轴夹钳报警 - M13轴驱动故障
23=M14轴夹钳报警 - M14轴驱动故障
24=M15轴夹钳报警 - M15轴驱动故障
32=常规报警 - 没有电源
33=常规报警 -紧急停车被按下
34=常规报警 -控制电路未启动
35=常规报警 -空气压力不足
36=常规报警 -电控柜温度不正常
37=常规报警 -热过载继电器跳闸
39=切屑传输带报警 - 切割传输带过载继电器跳闸
40=吸出器报警 - 左过载继电器跳闸
42=常规报警 -CNC 报警中
43=常规报警 -CNC1 报警中
44=常规报警 -CNC2 报警中
46=常规报警 - Not all CNC0, CNC1, CNC2 in manual mode
47=常规报警 - Not all CNC0, CNC1, CNC2 in automatic mode
48=心轴报警 - 心轴变频器故障
49=心轴报警 - 心轴变频器过载
50=心轴报警 - 心轴不旋转
51=心轴报警 - 速度不正确
52=心轴报警 - 刀具松开夹钳暂停
53=心轴报警 - 刀具夹钳夹紧暂停
54=心轴报警 - 刀具夹紧，限位器开关故障
55=心轴报警 - 刀具安装不正确
56=更换刀具报警 - 心轴上出现未知刀具
57=SPINDLE ALARM - Overload Relay Tripped Module Spindle Cooling
58=心轴报警 - 心轴冷却流量计CDI模块报警
62=心轴报警 - 主轴过度振动
63=心轴报警 - 主轴温度过高
64=X轴报警 - X轴正向超行程
65=X轴报警 - X轴反向超行程
66=Y轴报警 - Y轴正向超行程
67=Y轴报警 - Y轴反向超行程
68=Z轴报警 - Z轴正向超行程
69=Z轴报警 - Z轴反向超行程
70=B轴报警 - B轴正向超行程
71=B轴报警 - B轴反向超行程
72=C轴报警 - C轴正向超行程
73=C轴报警 - C轴反向超行程
74=P轴报警 - P轴正向超行程
75=P轴报警 - P轴反向超行程
76=H轴报警 - H轴正向超行程
77=H轴报警 - H轴反向超行程
78=W轴报警 - W轴正向超行程
79=W轴报警 - W轴反向超行程
80=刀具更换报警 - 1号刀具循环不能卸载
81=刀具更换报警 - 1号刀具循环不能装载
82=刀具更换报警 - 2号刀具循环不能卸载
83=刀具更换报警 - 2号刀具循环不能装载
84=刀具更换报警 - 3号刀具循环不能卸载
85=刀具更换报警 - 3号刀具循环不能装载
86=刀具更换报警 - 4号刀具循环不能卸载
87=刀具更换报警 - 4号刀具循环不能装载
88=刀具更换报警 - 5号刀具循环不能卸载
89=刀具更换报警 - 5号刀具循环不能装载
90=刀具更换报警 - 6号刀具循环不能卸载
91=刀具更换报警 - 6号刀具循环不能装载
92=刀具更换报警 - 7号刀具循环不能卸载
93=刀具更换报警 - 7号刀具循环不能装载
94=刀具更换报警 - 8号刀具循环不能卸载
95=刀具更换报警 - 8号刀具循环不能装载
96=刀具更换报警 - 9号刀具循环不能卸载
97=刀具更换报警 - 9号刀具循环不能装载
98=刀具更换报警 - 10号刀具循环不能卸载
99=刀具更换报警 - 10号刀具循环不能装载
100=刀具更换报警 - 11号刀具循环不能卸载
101=刀具更换报警 - 11号刀具循环不能装载
102=刀具更换报警 - 12号刀具循环不能卸载
103=刀具更换报警 - 12号刀具循环不能装载
104=TOOL MAGAZINE ALARM - Tool magazine hook not disengagement
105=TOOL MAGAZINE ALARM - Cycle started with spindle potential collision with tool magazine
106=TOOL MAGAZINE ALARM - Tool magazine hook not out encumbrance
107=夹钳报警 - 高压仍在启动中暂停
108=轴警报-工具和前护板之间可能发生碰撞
115=夹钳报警 - 10号夹钳不在正确位置
116=夹钳报警 - 11号夹钳不在正确位置
117=夹钳报警 - 12号夹钳不在正确位置
118=夹钳报警 - 13号夹钳不在正确位置
119=夹钳报警 - 14号夹钳不在正确位置
120=夹钳报警 - 15号夹钳不在正确位置
124=夹钳报警 - 发现夹钳数目不正确
125=VICES CHECK ALARM - Error in Vices Position from PC : out of range
136=VICES ALARM - Motorized vices power supply not OK
138=PRECISION BARRIER ALARM - Barrier not eingaged
139=PRECISION BARRIER ALARM - Barrier not diseingaged
140=PRECISION BARRIER ALARM - Wrong position at zero
141=PRECISION BARRIER ALARM - Wrong probing index
142=PRECISION BARRIER ALARM - Piece not found
143=POSITIONING ALARM - Piece badly placed at barrier
154=BARRIER ALARM - DX4 Barrier not in X4R position
155=BARRIER ALARM - Faulty limit switches DX4 barrier
156=BARRIER ALARM - SX1 Barrier not in X1L position
157=BARRIER ALARM - DX4 Barrier not in X3R position
158=BARRIER ALARM - DX4 Barrier not in X2R position
159=BARRIER ALARM - DX4 Barrier not in X1R position
160=挡板报警 - SX1挡板不够高
161=挡板报警 - SX1挡板不够低
166=挡板报警 - DX4挡板不够高
167=挡板报警 - DX4挡板不够低
176=工作台报警 - 工作台不后退：检查传感器
177=工作台报警 - 工作台不后退：检查电动阀EV
178=工作台报警 - 工作台不前进：检查传感器
179=工作台报警 - 工作台不前进：检查电动阀EV
180=工作台报警 - 工作台后退/前进限位开关故障
198=LUBRICA报警 - 常规Lubrica液位报警
199=LUBRICA ALARM - High Normal Lubrica level
200=PROBE MARPOSS ALARM - Probe already flush at start of contact
201=PROBE MARPOSS ALARM - Workpiece not detected by probe
202=PROBE MARPOSS ALARM - Probe index error
203=PROBE MARPOSS ALARM - Marposs probe error
204=PROBE MARPOSS ALARM - Marposs probe battery discharged
205=PROBE MARPOSS ALARM - Probe still flush after end of contact
206=PROBE MARPOSS ALARM - Correction values too big: verify probe
212=SLIDE GREASING ALARM - Low grease level
213=SLIDE GREASING ALARM - pump/electrovalve anomaly
214=SLIDE GREASING ALARM - Execution failure due to too many working hours
215=SLIDE GREASING ALARM - Sensor switching failure on single greasing
224=软件报警 - 错误打开/关闭文件: Path_conf.txt
225=软件报警 - 错误打开文件: Config.par
226=软件报警 - 错误打开文件: Tools.txt
227=软件报警 - 错误打开文件: Heads.txt
228=软件报警 - 刀具调用错误
229=软件报警-关闭文件错误:Config.Par/Tools.txt/Heads.txt
230=软件报警 - 文件读取错误
231=软件报警 - 错误打开文件: Variables.txt
232=软件报警 - 错误关闭文件: Variables.txt
233=软件报警 - 数据转换驱动丢失
234=软件报警 - 文件Confmac.CT4出错
235=软件报警 - 数值超出例行ISO CNC检查门槛
236=SOFTWARE ALARM - Tool table not loaded alarm (carry out M209)
237=软件报警 - X - Y - Z 轴移动报警
243=夹钳报警 - 10号夹钳不在位置上
244=夹钳报警 - 11号夹钳不在位置上
245=夹钳报警 - 12号夹钳不在位置上
246=夹钳报警 - 13号夹钳不在位置上
247=夹钳报警 - 14号夹钳不在位置上
248=夹钳报警 - 15号夹钳不在位置上
252=夹钳报警 - 在定位期间微动开关缺失
253=夹钳报警 - 在定位检查期间未发现微动开关
256=GENERAL ALARM - Error load ISOMG in memory
257=GENERAL ALARM - Timeout loading ISOMG in memory
260=CNC从动装置报警-在主动装置与从动装置之间手动/自动异步性
270=SIDEGUARD ALARM - Side Guard or tunnel LH not closed
271=SIDEGUARD ALARM - Side Guard or tunnel RH not closed
272=FRONTGUARD ALARM - Time Out Front Guard not closed : check the sensor
273=FRONTGUARD ALARM - Time Out Front Guard not closed : check the EV
274=FRONTGUARD ALARM - Time Out Front Guard not opened : check the sensor
275=FRONTGUARD ALARM - Time Out Front Guard not opened : check the EV
276=FRONTGUARD ALARM - Faulty Microswitch Front Guard
282=REARGUARD ALARM - Rear Guard LH not closed
283=REARGUARD ALARM - Rear Guard RH not closed
286=FRONTGUARD ALARM - Safety Controller not active with frontguard closed
298=FRONTGUARD ALARM - Guard sensitive edge triggered
320=夹钳牵引报警 -X轴夹钳牵引衔接暂停：检查传感器
321=夹钳牵引报警 -X轴夹钳牵引衔接暂停：检查电动阀EV
322=夹钳牵引报警 -X轴夹钳牵引脱离暂停：检查传感器
323=夹钳牵引报警 -X轴夹钳牵引脱离暂停：检查电动阀EV
324=夹钳牵引报警 -X轴夹钳牵引限位开关故障
342=CLAMP DETECTION ALARM - Clamp detection engagement timeout 
343=CLAMP DETECTION ALARM - Clamp detection disengagement timeout 
371=VICES ALARM - High Pressure Vice 10 not active
372=VICES ALARM - High Pressure Vice 11 not active
373=VICES ALARM - High Pressure Vice 12 not active
374=VICES ALARM - High Pressure Vice 13 not active
375=VICES ALARM - High Pressure Vice 14 not active
376=VICES ALARM - High Pressure Vice 15 not active
384=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the sensor
385=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the EV
386=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
387=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
388=GUARD ALARM - Faulty limit switches Down Guard
394=GUARD ALARM - Time Out Up Guard not open (down movement) : check the sensor
395=GUARD ALARM - Time Out Up Guard not open (down movement) : check the EV
396=GUARD ALARM - Time Out Up Guard not close (up movement) : check the sensor
397=GUARD ALARM - Time Out Up Guard not close (up movement) : check the EV
402=TOOL ALARM - Tool T1 broken
403=TOOL ALARM - Tool T2 broken
404=TOOL ALARM - Tool T3 broken
405=TOOL ALARM - Tool T4 broken
406=TOOL ALARM - Tool T5 broken
407=TOOL ALARM - Tool T6 broken
408=TOOL ALARM - Tool T7 broken
409=TOOL ALARM - Tool T8 broken
410=TOOL ALARM - Tool T9 broken
411=TOOL ALARM - Tool T10 broken
412=TOOL ALARM - Tool T11 broken
413=TOOL ALARM - Tool T12 broken
414=TOOL ALARM - Drill not alive
416=GANTRY ALARM - Clamps not engaged in gantry
417=GANTRY ALARM - Clamps not released from gantry
418=VICES AXES ALARM - Vices axes positions not congruent (lost encoder positions)
419=TOOL CHANGE ALARM - Inconsistency between tool theoretically present and tool presence sensor alarm
420=刀具检查警报 - 刀具损坏
421=工具检查警报 - 工具完整性检查设备不工作
438=VICE AXIS ALARM - Vice axis M10 in Positive Overtravel
439=VICE AXIS ALARM - Vice axis M10 in Negative Overtravel
440=VICE AXIS ALARM - Vice axis M11 in Positive Overtravel
441=VICE AXIS ALARM - Vice axis M11 in Negative Overtravel
442=VICE AXIS ALARM - Vice axis M12 in Positive Overtravel
443=VICE AXIS ALARM - Vice axis M12 in Negative Overtravel
444=VICE AXIS ALARM - Vice axis M13 in Positive Overtravel
445=VICE AXIS ALARM - Vice axis M13 in Negative Overtravel
446=VICE AXIS ALARM - Vice axis M14 in Positive Overtravel
447=VICE AXIS ALARM - Vice axis M14 in Negative Overtravel
448=VICE AXIS ALARM - Vice axis M15 in Positive Overtravel
449=VICE AXIS ALARM - Vice axis M15 in Negative Overtravel
475=CONFIGURATION ALARM - Initialization variables PLC error
476=CONFIGURATION ALARM - Error reading CONFMAC file
477=CONFIGURATION ALARM - Error loading manual function (MGPilot)
478=CONFIGURATION ALARM - Error loading manual function (REM_CTRL)
480=ALARM AXIS X - Voltage level low encoder battery
481=ALARM AXIS Y - Voltage level low encoder battery
482=ALARM AXIS Z - Voltage level low encoder battery
483=ALARM AXIS A - Voltage level low encoder battery
484=ALARM AXIS W - Voltage level low encoder battery
487=ALARM AXIS X - Voltage level low encoder battery and absolute position lost
488=ALARM AXIS Y - Voltage level low encoder battery and absolute position lost
489=ALARM AXIS Z - Voltage level low encoder battery and absolute position lost
490=ALARM AXIS A - Voltage level low encoder battery and absolute position lost
491=ALARM AXIS W - Voltage level low encoder battery and absolute position lost
496=ALARM AXIS X - Overflow on the maximum revolutions of the absolute multiturn encoder
497=ALARM AXIS Y - Overflow on the maximum revolutions of the absolute multiturn encoder
498=ALARM AXIS Z - Overflow on the maximum revolutions of the absolute multiturn encoder
499=ALARM AXIS A - Overflow on the maximum revolutions of the absolute multiturn encoder
500=ALARM AXIS W - Overflow on the maximum revolutions of the absolute multiturn encoder
503=ALARM AXIS X - Absolute encoder position not initialized
504=ALARM AXIS Y - Absolute encoder position not initialized
505=ALARM AXIS Z - Absolute encoder position not initialized
506=ALARM AXIS A - Absolute encoder position not initialized
507=ALARM AXIS W - Absolute encoder position not initialized
512=ALARM AXIS X - Absolute encoder reset function failed
513=ALARM AXIS Y - Absolute encoder reset function failed
514=ALARM AXIS Z - Absolute encoder reset function failed
515=ALARM AXIS A - Absolute encoder reset function failed
516=ALARM AXIS W - Absolute encoder reset function failed
519=ALARM AXIS X - Main circuit DC voltage is lower than standard value
520=ALARM AXIS Y - Main circuit DC voltage is lower than standard value
521=ALARM AXIS Z - Main circuit DC voltage is lower than standard value
522=ALARM AXIS A - Main circuit DC voltage is lower than standard value
523=ALARM AXIS W - Main circuit DC voltage is lower than standard value
528=ALARM AXIS X - Lack of an input phase
529=ALARM AXIS Y - Lack of an input phase
530=ALARM AXIS Z - Lack of an input phase
531=ALARM AXIS A - Lack of an input phase
532=ALARM AXIS W - Lack of an input phase
535=ALARM AXIS X - Motor speed is in overshoot compared to maximum value
536=ALARM AXIS Y - Motor speed is in overshoot compared to maximum value
537=ALARM AXIS Z - Motor speed is in overshoot compared to maximum value
538=ALARM AXIS A - Motor speed is in overshoot compared to maximum value
539=ALARM AXIS W - Motor speed is in overshoot compared to maximum value
544=ALARM PLC IEC - Timeout PLC IEC not alive
545=ALARM PLC IEC - COM communication error with inverter 0
560=ALARM PLC IEC - COM communication error with drive axis X
561=ALARM PLC IEC - COM communication error with drive axis Y
562=ALARM PLC IEC - COM communication error with drive axis Z
563=ALARM PLC IEC - COM communication error with drive axis A
564=ALARM PLC IEC - COM communication error with drive axis W

[MSG]
1=操作手信息 - 轴未被参照
2=操作手信息 - 设备处于保持状态
3=操作手信息 - 在心轴上未知刀具
4=操作手信息 - 在自动循环期间电位计为零
5=操作手信息 - 由于刀架设备处于保持状态
6=操作手信息 - 由于左夹钳设备处于保持状态
7=操作手信息 - 由于右夹钳设备处于保持状态
8=操作手信息 - 由于心轴设备处于保持状态
9=OPERATOR MESSAGE - Machine in HOLD condition from Front or Rear Guard
10=OPERATOR MESSAGE - Tool magazine in potential collision with left side cover of the machine  
11=OPERATOR MESSAGE - Spindle in potential collision with tool magazine
12=操作手信息- FATM处于激活状态 停止执行
13=OPERATOR MESSAGE - Hold opening / closing Front Guard from Y, B, C axes position
14=操作手信息- 注意：在输入未保留时短路可能
15=OPERATOR MESSAGE - Potential collision between tool and front guard
16=操作手信息- 只能在前防护板放下时才能松开在旋转的刀具
25=OPERATOR MESSAGE - Automatic greasing disabled
27=OPERATOR MESSAGE - No security common outputs with safety switch on
30=OPERATOR MESSAGE - Bridge password initialization done, restart
31=OPERATOR MESSAGE - Counters file writing error
77=OPERATOR MESSAGE - loading manual functions Error (MG Pilot)
78=OPERATOR MESSAGE - loading manual functions Error (REM_CTRL)
80=OPERATOR MESSAGE - X axis motor in overload prealarm
81=OPERATOR MESSAGE - Y axis motor in overload prealarm
82=OPERATOR MESSAGE - Z axis motor in overload prealarm
83=OPERATOR MESSAGE - A axis motor in overload prealarm
84=OPERATOR MESSAGE - W axis motor in overload prealarm
88=OPERATOR MESSAGE - Voltage level low X axis encoder battery and absolute position lost
89=OPERATOR MESSAGE - Voltage level low Y axis encoder battery and absolute position lost
90=OPERATOR MESSAGE - Voltage level low Z axis encoder battery and absolute position lost
91=OPERATOR MESSAGE - Voltage level low A axis encoder battery and absolute position lost
92=OPERATOR MESSAGE - Voltage level low W axis encoder battery and absolute position lost
96=OPERATOR MESSAGE - Voltage level low X axis encoder battery
97=OPERATOR MESSAGE - Voltage level low Y axis encoder battery
98=OPERATOR MESSAGE - Voltage level low Z axis encoder battery
99=OPERATOR MESSAGE - Voltage level low A axis encoder battery
100=OPERATOR MESSAGE - Voltage level low W axis encoder battery
104=OPERATOR MESSAGE - X axis absolute encoder position not initialized
105=OPERATOR MESSAGE - Y axis absolute encoder position not initialized
106=OPERATOR MESSAGE - Z axis absolute encoder position not initialized
107=OPERATOR MESSAGE - A axis absolute encoder position not initialized
108=OPERATOR MESSAGE - W axis absolute encoder position not initialized
112=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn X axis encoder
113=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Y axis encoder
114=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Z axis encoder
115=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn A axis encoder
116=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn W axis encoder
