[ALARM]
1=ALARM AXIS X - Fault on drive axis X
2=ALARM AXIS Y - Fault on drive axis Y
3=ALARM AXIS Z - Fault on drive axis Z
4=ALARM AXIS B - Fault on drive axis B
5=ALARM AXIS C - Fault on drive axis C
6=ALARM AXIS W - Fault on drive axis W
9=GENERAL ALARM - No power to the axes drives
15=SOFTWARE ALARM - Alarm counter read writing
19=ALARM VICE AXIS M10 - Fault on drive vice axis M10
20=ALARM VICE AXIS M11 - Fault on drive vice axis M11
21=ALARM VICE AXIS M12 - Fault on drive vice axis M12
22=ALARM VICE AXIS M13 - Fault on drive vice axis M13
23=ALARM VICE AXIS M14 - Fault on drive vice axis M14
24=ALARM VICE AXIS M15 - Fault on drive vice axis M15
32=GENERAL ALARM - Power Supplies Not Present
33=GENERAL ALARM - Emergency stop pressed
34=GENERAL ALARM - Control circuits not energized
35=GENERAL ALARM - Insufficient air pressure
36=GENERAL ALARM - Electrical cabinet temperature not ok
37=GENERAL ALARM - Thermal overload relays tripped
39=SWARF CONVEYOR ALARM - Overload Relay Tripped Cuttings Conveyor
40=ASPIRATOR ALARM - Overload Relay Tripped 
42=GENERAL ALARM - CNC in alarm
43=GENERAL ALARM - CNC1 in alarm
44=GENERAL ALARM - CNC2 in alarm
46=GENERAL ALARM - Not all CNC0, CNC1, CNC2 in manual mode
47=GENERAL ALARM - Not all CNC0, CNC1, CNC2 in automatic mode
48=SPINDLE ALARM - Fault on spindle inverter
49=SPINDLE ALARM - Spindle inverter overloaded
50=SPINDLE ALARM - Spindle not rotating
51=SPINDLE ALARM - Speed not correct 
52=SPINDLE ALARM - Time out tool unclamping
53=SPINDLE ALARM - Time out tool clamping
54=SPINDLE ALARM - Faulty limit switches, tool clamping
55=SPINDLE ALARM - Tool not mounted correctly.
56=SPINDLE ALARM - Unknown tool on spindle
57=SPINDLE ALARM - Overload Relay Tripped Module Spindle Cooling
58=SPINDLE ALARM - Flowmeter CDI Module Spindle Cooling in Alarm
62=SPINDLE ALARM - Excessive vibrations on the spindle
63=SPINDLE ALARM - Excessive temperature on the spindle
64=AXIS ALARM - Axis X in Positive Overtravel
65=AXIS ALARM - Axis X in Negative Overtravel
66=AXIS ALARM - Axis Y in Positive Overtravel
67=AXIS ALARM - Axis Y in Negative Overtravel
68=AXIS ALARM - Axis Z in Positive Overtravel
69=AXIS ALARM - Axis Z in Negative Overtravel
70=AXIS ALARM - Axis B in Positive Overtravel
71=AXIS ALARM - Axis B in Negative Overtravel
72=AXIS ALARM - Axis C in Positive Overtravel
73=AXIS ALARM - Axis C in Negative Overtravel
74=AXIS ALARM - Axis P in Positive Overtravel
75=AXIS ALARM - Axis P in Negative Overtravel
76=AXIS ALARM - Axis H in Positive Overtravel
77=AXIS ALARM - Axis H in Negative Overtravel
78=AXIS ALARM - Axis W in Positive Overtravel
79=AXIS ALARM - Axis W in Negative Overtravel
80=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.1
81=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.1
82=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.2
83=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.2
84=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.3
85=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.3
86=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.4
87=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.4
88=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.5
89=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.5
90=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.6
91=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.6
92=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.7
93=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.7
94=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.8
95=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.8
96=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.9
97=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.9
98=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.10
99=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.10
100=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.11
101=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.11
102=TOOL CHANGE ALARM - Impossibile Unloading Cycle Tool n.12
103=TOOL CHANGE ALARM - Impossibile Loading Cycle Tool n.12
104=TOOL MAGAZINE ALARM - Tool magazine hook not disengagement
105=TOOL MAGAZINE ALARM - Cycle started with spindle potential collision with tool magazine
106=TOOL MAGAZINE ALARM - Tool magazine hook not out encumbrance
107=VICES ALARM - Time Out High Pressure still active
108=TENGELY RIASZTÁS - Potenciális ütközés a szerszám és az elso védoburkolatok között
115=VICES ALARM - Vice 10 not in the correct position
116=VICES ALARM - Vice 11 not in the correct position
117=VICES ALARM - Vice 12 not in the correct position
118=VICES ALARM - Vice 13 not in the correct position
119=VICES ALARM - Vice 14 not in the correct position
120=VICES ALARM - Vice 15 not in the correct position
124=VICES ALARM - Incorrect Number of Vices Founded
125=VICES CHECK ALARM - Error in Vices Position from PC : out of range
136=VICES ALARM - Motorized vices power supply not OK
138=PRECISION BARRIER ALARM - Barrier not eingaged
139=PRECISION BARRIER ALARM - Barrier not diseingaged
140=PRECISION BARRIER ALARM - Wrong position at zero
141=PRECISION BARRIER ALARM - Wrong probing index
142=PRECISION BARRIER ALARM - Piece not found
143=POSITIONING ALARM - Piece badly placed at barrier
154=BARRIER ALARM - DX4 Barrier not in X4R position
155=BARRIER ALARM - Faulty limit switches DX4 barrier
156=BARRIER ALARM - SX1 Barrier not in X1L position
157=BARRIER ALARM - DX4 Barrier not in X3R position
158=BARRIER ALARM - DX4 Barrier not in X2R position
159=BARRIER ALARM - DX4 Barrier not in X1R position
160=BARRIER ALARM - SX1 Barrier not high
161=BARRIER ALARM - SX1 Barrier not low
166=BARRIER ALARM - DX4 Barrier not high
167=BARRIER ALARM - DX4 Barrier not low
176=TABLE ALARM - Time Out Table not backward : check the sensor
177=TABLE ALARM - Time Out Table not backward : check the EV
178=TABLE ALARM - Time Out Table not forward : check the sensor
179=TABLE ALARM - Time Out Table not forward : check the EV
180=TABLE ALARM - Faulty limit switches backward/forward Table
198=LUBRICA ALARM - Low Normal Lubrica level 
199=LUBRICA ALARM - High Normal Lubrica level
200=PROBE MARPOSS ALARM - Probe already flush at start of contact
201=PROBE MARPOSS ALARM - Workpiece not detected by probe
202=PROBE MARPOSS ALARM - Probe index error
203=PROBE MARPOSS ALARM - Marposs probe error
204=PROBE MARPOSS ALARM - Marposs probe battery discharged
205=PROBE MARPOSS ALARM - Probe still flush after end of contact
206=PROBE MARPOSS ALARM - Correction values too big: verify probe
212=SLIDE GREASING ALARM - Low grease level
213=SLIDE GREASING ALARM - pump/electrovalve anomaly
214=SLIDE GREASING ALARM - Execution failure due to too many working hours
215=SLIDE GREASING ALARM - Sensor switching failure on single greasing
224=SOFTWARE ALARM - Wrong opening/closing file : Path_conf.txt
225=SOFTWARE ALARM - Wrong opening file : Config.par
226=SOFTWARE ALARM - Wrong opening file : Tools.txt
227=SOFTWARE ALARM - Wrong opening file : Heads.txt
228=SOFTWARE ALARM - Error in tool call
229=SOFTWARE ALARM - Wrong closing file : Config.Par/Tools.txt/Heads.txt 
230=SOFTWARE ALARM - Error reading file
231=SOFTWARE ALARM - Wrong opening file : Variables.txt
232=SOFTWARE ALARM - Wrong closing file : Variables.txt
233=SOFTWARE ALARM - Data conversion driver missing
234=SOFTWARE ALARM - Error in Machine Configuration 
235=SOFTWARE ALARM - Value beyond thresholds in Routine ISO CNC checks
236=SOFTWARE ALARM - Tool table not loaded alarm (carry out M209)
237=SOFTWARE ALARM - Alarm movement Axis X - Y - Z
243=VICES ALARM - Vice 10 not in position
244=VICES ALARM - Vice 11 not in position
245=VICES ALARM - Vice 12 not in position
246=VICES ALARM - Vice 13 not in position
247=VICES ALARM - Vice 14 not in position
248=VICES ALARM - Vice 15 not in position
252=VICES ALARM - Microswitch Vices lost during positioning
253=VICES ALARM - Microswitch not found during position check
256=GENERAL ALARM - Error load ISOMG in memory
257=GENERAL ALARM - Timeout loading ISOMG in memory
260=ALARM CNC SLAVE - Asynchrony Manual/Automatic between Master and Slave
270=SIDEGUARD ALARM - Side Guard or tunnel LH not closed
271=SIDEGUARD ALARM - Side Guard or tunnel RH not closed
272=FRONTGUARD ALARM - Time Out Front Guard not closed : check the sensor
273=FRONTGUARD ALARM - Time Out Front Guard not closed : check the EV
274=FRONTGUARD ALARM - Time Out Front Guard not opened : check the sensor
275=FRONTGUARD ALARM - Time Out Front Guard not opened : check the EV
276=FRONTGUARD ALARM - Faulty Microswitch Front Guard
282=REARGUARD ALARM - Rear Guard LH not closed
283=REARGUARD ALARM - Rear Guard RH not closed
286=FRONTGUARD ALARM - Safety Controller not active with frontguard closed
298=FRONTGUARD ALARM - Guard sensitive edge triggered
320=ALARM VICES DRAG - Time out X Axis vices drag eingagement : check the sensor
321=ALARM VICES DRAG - Time out X Axis vices drag eingagement : check the EV
322=ALARM VICES DRAG - Time out X Axis vices drag diseingagement : check the sensor
323=ALARM VICES DRAG - Time out X Axis vices drag diseingagement : check the EV
324=ALARM VICES DRAG - Faulty limit switches X Axis vices drag
342=CLAMP DETECTION ALARM - Clamp detection engagement timeout 
343=CLAMP DETECTION ALARM - Clamp detection disengagement timeout 
371=VICES ALARM - High Pressure Vice 10 not active
372=VICES ALARM - High Pressure Vice 11 not active
373=VICES ALARM - High Pressure Vice 12 not active
374=VICES ALARM - High Pressure Vice 13 not active
375=VICES ALARM - High Pressure Vice 14 not active
376=VICES ALARM - High Pressure Vice 15 not active
384=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the sensor
385=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the EV
386=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
387=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
388=GUARD ALARM - Faulty limit switches Down Guard
394=GUARD ALARM - Time Out Up Guard not open (down movement) : check the sensor
395=GUARD ALARM - Time Out Up Guard not open (down movement) : check the EV
396=GUARD ALARM - Time Out Up Guard not close (up movement) : check the sensor
397=GUARD ALARM - Time Out Up Guard not close (up movement) : check the EV
402=TOOL ALARM - Tool T1 broken
403=TOOL ALARM - Tool T2 broken
404=TOOL ALARM - Tool T3 broken
405=TOOL ALARM - Tool T4 broken
406=TOOL ALARM - Tool T5 broken
407=TOOL ALARM - Tool T6 broken
408=TOOL ALARM - Tool T7 broken
409=TOOL ALARM - Tool T8 broken
410=TOOL ALARM - Tool T9 broken
411=TOOL ALARM - Tool T10 broken
412=TOOL ALARM - Tool T11 broken
413=TOOL ALARM - Tool T12 broken
414=TOOL ALARM - Drill not alive
416=GANTRY ALARM - Clamps not engaged in gantry
417=GANTRY ALARM - Clamps not released from gantry
418=VICES AXES ALARM - Vices axes positions not congruent (lost encoder positions)
419=TOOL CHANGE ALARM - Inconsistency between tool theoretically present and tool presence sensor alarm
420=TOOL CHECK ALARM - Broken tool
421=TOOL CHECK ALARM - Tool integrity check device not working
438=VICE AXIS ALARM - Vice axis M10 in Positive Overtravel
439=VICE AXIS ALARM - Vice axis M10 in Negative Overtravel
440=VICE AXIS ALARM - Vice axis M11 in Positive Overtravel
441=VICE AXIS ALARM - Vice axis M11 in Negative Overtravel
442=VICE AXIS ALARM - Vice axis M12 in Positive Overtravel
443=VICE AXIS ALARM - Vice axis M12 in Negative Overtravel
444=VICE AXIS ALARM - Vice axis M13 in Positive Overtravel
445=VICE AXIS ALARM - Vice axis M13 in Negative Overtravel
446=VICE AXIS ALARM - Vice axis M14 in Positive Overtravel
447=VICE AXIS ALARM - Vice axis M14 in Negative Overtravel
448=VICE AXIS ALARM - Vice axis M15 in Positive Overtravel
449=VICE AXIS ALARM - Vice axis M15 in Negative Overtravel
475=CONFIGURATION ALARM - Initialization variables PLC error
476=CONFIGURATION ALARM - Error reading CONFMAC file
477=CONFIGURATION ALARM - Error loading manual function (MGPilot)
478=CONFIGURATION ALARM - Error loading manual function (REM_CTRL)
480=ALARM AXIS X - Voltage level low encoder battery
481=ALARM AXIS Y - Voltage level low encoder battery
482=ALARM AXIS Z - Voltage level low encoder battery
483=ALARM AXIS A - Voltage level low encoder battery
484=ALARM AXIS W - Voltage level low encoder battery
487=ALARM AXIS X - Voltage level low encoder battery and absolute position lost
488=ALARM AXIS Y - Voltage level low encoder battery and absolute position lost
489=ALARM AXIS Z - Voltage level low encoder battery and absolute position lost
490=ALARM AXIS A - Voltage level low encoder battery and absolute position lost
491=ALARM AXIS W - Voltage level low encoder battery and absolute position lost
496=ALARM AXIS X - Overflow on the maximum revolutions of the absolute multiturn encoder
497=ALARM AXIS Y - Overflow on the maximum revolutions of the absolute multiturn encoder
498=ALARM AXIS Z - Overflow on the maximum revolutions of the absolute multiturn encoder
499=ALARM AXIS A - Overflow on the maximum revolutions of the absolute multiturn encoder
500=ALARM AXIS W - Overflow on the maximum revolutions of the absolute multiturn encoder
503=ALARM AXIS X - Absolute encoder position not initialized
504=ALARM AXIS Y - Absolute encoder position not initialized
505=ALARM AXIS Z - Absolute encoder position not initialized
506=ALARM AXIS A - Absolute encoder position not initialized
507=ALARM AXIS W - Absolute encoder position not initialized
512=ALARM AXIS X - Absolute encoder reset function failed
513=ALARM AXIS Y - Absolute encoder reset function failed
514=ALARM AXIS Z - Absolute encoder reset function failed
515=ALARM AXIS A - Absolute encoder reset function failed
516=ALARM AXIS W - Absolute encoder reset function failed
519=ALARM AXIS X - Main circuit DC voltage is lower than standard value
520=ALARM AXIS Y - Main circuit DC voltage is lower than standard value
521=ALARM AXIS Z - Main circuit DC voltage is lower than standard value
522=ALARM AXIS A - Main circuit DC voltage is lower than standard value
523=ALARM AXIS W - Main circuit DC voltage is lower than standard value
528=ALARM AXIS X - Lack of an input phase
529=ALARM AXIS Y - Lack of an input phase
530=ALARM AXIS Z - Lack of an input phase
531=ALARM AXIS A - Lack of an input phase
532=ALARM AXIS W - Lack of an input phase
535=ALARM AXIS X - Motor speed is in overshoot compared to maximum value
536=ALARM AXIS Y - Motor speed is in overshoot compared to maximum value
537=ALARM AXIS Z - Motor speed is in overshoot compared to maximum value
538=ALARM AXIS A - Motor speed is in overshoot compared to maximum value
539=ALARM AXIS W - Motor speed is in overshoot compared to maximum value
544=ALARM PLC IEC - Timeout PLC IEC not alive
545=ALARM PLC IEC - COM communication error with inverter 0
560=ALARM PLC IEC - COM communication error with drive axis X
561=ALARM PLC IEC - COM communication error with drive axis Y
562=ALARM PLC IEC - COM communication error with drive axis Z
563=ALARM PLC IEC - COM communication error with drive axis A
564=ALARM PLC IEC - COM communication error with drive axis W

[MSG]
1=OPERATOR MESSAGE - Axes not referenced
2=OPERATOR MESSAGE - Machine in HOLD condition
3=OPERATOR MESSAGE - Unknown tool on spindle
4=OPERATOR MESSAGE - Potentiometer at Zero during Automatic Cycle
5=OPERATOR MESSAGE - Machine in HOLD condition from Tool Stock
6=OPERATOR MESSAGE - Machine in HOLD condition from Vices LF Zone
7=OPERATOR MESSAGE - Machine in HOLD condition from Vices RT Zone
8=OPERATOR MESSAGE - Machine in HOLD condition from Spindle
9=OPERATOR MESSAGE - Machine in HOLD condition from Front or Rear Guard
10=OPERATOR MESSAGE - Tool magazine in potential collision with left side cover of the machine  
11=OPERATOR MESSAGE - Spindle in potential collision with tool magazine
12=OPERATOR MESSAGE - Block Execution FATM Active
13=OPERATOR MESSAGE - Hold opening / closing Front Guard from Y, B, C axes position
14=OPERATOR MESSAGE - Attention : Possible Short Circuit on Inputs Not Retentive
15=OPERATOR MESSAGE - Potential collision between tool and front guard
16=OPERATOR MESSAGE - Release Tool On.Spin. possible only with front guards down
25=OPERATOR MESSAGE - Automatic greasing disabled
27=OPERATOR MESSAGE - No security common outputs with safety switch on
30=OPERATOR MESSAGE - Bridge password initialization done, restart
31=OPERATOR MESSAGE - Counters file writing error
77=OPERATOR MESSAGE - loading manual functions Error (MG Pilot)
78=OPERATOR MESSAGE - loading manual functions Error (REM_CTRL)
80=OPERATOR MESSAGE - X axis motor in overload prealarm
81=OPERATOR MESSAGE - Y axis motor in overload prealarm
82=OPERATOR MESSAGE - Z axis motor in overload prealarm
83=OPERATOR MESSAGE - A axis motor in overload prealarm
84=OPERATOR MESSAGE - W axis motor in overload prealarm
88=OPERATOR MESSAGE - Voltage level low X axis encoder battery and absolute position lost
89=OPERATOR MESSAGE - Voltage level low Y axis encoder battery and absolute position lost
90=OPERATOR MESSAGE - Voltage level low Z axis encoder battery and absolute position lost
91=OPERATOR MESSAGE - Voltage level low A axis encoder battery and absolute position lost
92=OPERATOR MESSAGE - Voltage level low W axis encoder battery and absolute position lost
96=OPERATOR MESSAGE - Voltage level low X axis encoder battery
97=OPERATOR MESSAGE - Voltage level low Y axis encoder battery
98=OPERATOR MESSAGE - Voltage level low Z axis encoder battery
99=OPERATOR MESSAGE - Voltage level low A axis encoder battery
100=OPERATOR MESSAGE - Voltage level low W axis encoder battery
104=OPERATOR MESSAGE - X axis absolute encoder position not initialized
105=OPERATOR MESSAGE - Y axis absolute encoder position not initialized
106=OPERATOR MESSAGE - Z axis absolute encoder position not initialized
107=OPERATOR MESSAGE - A axis absolute encoder position not initialized
108=OPERATOR MESSAGE - W axis absolute encoder position not initialized
112=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn X axis encoder
113=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Y axis encoder
114=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Z axis encoder
115=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn A axis encoder
116=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn W axis encoder
