[ALARM]
1=ALLARME ASSE X - Anomalia azionamento asse X
2=ALLARME ASSE Y - Anomalia azionamento asse Y
3=ALLARME ASSE Z - Anomalia azionamento asse Z
4=ALLARME ASSE B - Anomalia azionamento asse B
5=ALLARME ASSE C - Anomalia azionamento asse C
6=ALLARME ASSE W - Anomalia azionamento asse W
9=ALLARME GENERALE - Assenza alimentazione agli azionamenti degli assi
15=ALLARME SOFTWARE - Allarme lettura scrittura contatori
19=ALLARME ASSE MORSA M10 - Anomalia azionamento asse Morsa M10
20=ALLARME ASSE MORSA M11 - Anomalia azionamento asse Morsa M11
21=ALLARME ASSE MORSA M12 - Anomalia azionamento asse Morsa M12
22=ALLARME ASSE MORSA M13 - Anomalia azionamento asse Morsa M13
23=ALLARME ASSE MORSA M14 - Anomalia azionamento asse Morsa M14
24=ALLARME ASSE MORSA M15 - Anomalia azionamento asse Morsa M15
32=ALLARME GENERALE - Alimentazioni non presenti
33=ALLARME GENERALE - Emergenza premuta
34=ALLARME GENERALE - Ausiliari non inseriti
35=ALLARME GENERALE - Pressione aria insufficiente
36=ALLARME GENERALE - Temperatura armadio non ok
37=ALLARME GENERALE - Termici scattati
39=ALLARME TRASP.TRUCIOLI - Termico trasportatore scattato
40=ALLARME ASPIRATORE - Termico aspiratore scattato
42=ALLARME GENERALE - CNC in allarme
43=ALLARME GENERALE - CNC1 in allarme
44=ALLARME GENERALE - CNC2 in allarme
46=ALLARME GENERALE - CNC0, CNC1, CNC2 non tutti in manuale
47=ALLARME GENERALE - CNC0, CNC1, CNC2 non tutti in automatico
48=ALLARME MANDRINO - Anomalia inverter mandrino
49=ALLARME MANDRINO - Inverter mandrino in sovraccarico
50=ALLARME MANDRINO - Mandrino non in rotazione
51=ALLARME MANDRINO - Velocita' non a regime
52=ALLARME MANDRINO - Time out sbloccaggio utensile
53=ALLARME MANDRINO - Time out bloccaggio utensile
54=ALLARME MANDRINO - Disfunzione F.C bloccaggio utensile
55=ALLARME MANDRINO - Utensile non agganciato correttamente
56=ALLARME MANDRINO - Utensile sconosciuto su mandrino
57=ALLARME MANDRINO - Termico Centralina di Raffreddamento Mandrino scattato
58=ALLARME MANDRINO - Flussostato Centralina di Raffreddamento Mandrino in allarme
62=ALLARME MANDRINO - Vibrazioni eccessive sul mandrino
63=ALLARME MANDRINO - Temperatura eccessiva sul mandrino
64=ALLARMI ASSI - Asse X in Extracorsa Positivo
65=ALLARMI ASSI - Asse X in Extracorsa Negativo
66=ALLARMI ASSI - Asse Y in Extracorsa Positivo
67=ALLARMI ASSI - Asse Y in Extracorsa Negativo
68=ALLARMI ASSI - Asse Z in Extracorsa Positivo
69=ALLARMI ASSI - Asse Z in Extracorsa Negativo
70=ALLARMI ASSI - Asse A in Extracorsa Positivo
71=ALLARMI ASSI - Asse A in Extracorsa Negativo
72=ALLARMI ASSI - Asse C in Extracorsa Positivo
73=ALLARMI ASSI - Asse C in Extracorsa Negativo
74=ALLARMI ASSI - Asse P in Extracorsa Positivo
75=ALLARMI ASSI - Asse P in Extracorsa Negativo
76=ALLARMI ASSI - Asse H in Extracorsa Positivo
77=ALLARMI ASSI - Asse H in Extracorsa Negativo
78=ALLARMI ASSI - Asse W in Extracorsa Positivo
79=ALLARMI ASSI - Asse W in Extracorsa Negativo
80=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 1
81=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 1
82=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 2
83=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 2
84=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 3
85=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 3
86=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 4
87=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 4
88=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 5
89=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 5
90=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 6
91=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 6
92=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 7
93=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 7
94=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 8
95=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 8
96=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 9
97=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 9
98=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 10
99=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 10
100=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 11
101=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 11
102=ALLARME CAMBIO UTENSILI - Impossibile depositare utensile 12
103=ALLARME CAMBIO UTENSILI - Impossibile prelevare utensile 12
104=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non disinserito
105=ALLARME MAGAZZINO UTENSILI - Ciclo iniziato con mandrino in potenziale collisione con magazzino
106=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non fuori ingombro
107=ALLARME MORSE - Alta Pressione attiva senza comando
108=ALLARMI ASSI - Potenziale collisione fra utensile e ripari anteriori
115=ALLARME MORSE - Morsa 10 non in posizione corretta
116=ALLARME MORSE - Morsa 11 non in posizione corretta
117=ALLARME MORSE - Morsa 12 non in posizione corretta
118=ALLARME MORSE - Morsa 13 non in posizione corretta
119=ALLARME MORSE - Morsa 14 non in posizione corretta
120=ALLARME MORSE - Morsa 15 non in posizione corretta
124=ALLARME MORSE - Conteggio morse errato
125=ALLARME MORSE - Errore pos. Morse da PC: valori fuori range
127=PREDISPOSTO: ALLARME MODULO SICUREZZA - Modulo di sicurezza in anomalia, controlla la word A2843
136=ALLARME MORSE - Alimentatore morse motorizzate in zona non OK
138=ALLARME BATTUTA DI PRECISIONE - Battuta non inserita
139=ALLARME BATTUTA DI PRECISIONE - Battuta non disinserita
140=ALLARME BATTUTA DI PRECISIONE - Errore posizione a riposo della battuta
141=ALLARME BATTUTA DI PRECISIONE - Errore indice di tastatura
142=ALLARME BATTUTA DI PRECISIONE - Pezzo non trovato
143=ALLARME DI POSIZIONAMENTO - Pezzo appoggiato male alla battuta di riferimento
154=ALLARME BATTUTE - Battuta DX4 non in posizione X4R
155=ALLARME BATTUTE - Disfunzione Finecorsa Battuta DX4
156=ALLARME BATTUTE - Battuta SX1 non in posizione X1L
157=ALLARME BATTUTE - Battuta DX4 non in posizione X3R
158=ALLARME BATTUTE - Battuta DX4 non in posizione X2R
159=ALLARME BATTUTE - Battuta DX4 non in posizione X1R
160=ALLARME BATTUTE - Battuta SX1 non alta
161=ALLARME BATTUTE - Battuta SX1 non bassa
166=ALLARME BATTUTE - Battuta DX4 non alta
167=ALLARME BATTUTE - Battuta DX4 non bassa
176=ALLARME TAVOLA - Tavola non avanti : controlla il sensore
177=ALLARME TAVOLA - Tavola non avanti : controlla la EV
178=ALLARME TAVOLA - Tavola non indietro : controlla il sensore
179=ALLARME TAVOLA - Tavola non indietro : controlla la EV
180=ALLARME TAVOLA - Disfunzione Finecorsa Tavola
198=ALLARME LUBRICA - Livello lubrica normale basso
199=ALLARME LUBRICA - Livello lubrica normale alto
200=ALLARME TASTATORE MARPOSS - Tastatore già in battuta ad inizio tastata
201=ALLARME TASTATORE MARPOSS - Pezzo non rilevato da tastatore
202=ALLARME TASTATORE MARPOSS - Errore indice tastatore
203=ALLARME TASTATORE MARPOSS - Tastatore Marposs in errore
204=ALLARME TASTATORE MARPOSS - Batteria scarica tastatore Marposs
205=ALLARME TASTATORE MARPOSS - Tastatore ancor in battuta dopo fine tastata
206=ALLARME TASTATORE MARPOSS - Correzioni troppo grandi: verificare il tastatore
212=ALLARME INGRASSAGGIO GUIDE - Livello grasso basso
213=ALLARME INGRASSAGGIO GUIDE - Anomalia pompa/elettrovalvola
214=ALLARME INGRASSAGGIO GUIDE - Mancata esecuzione per troppe ore lavorative
215=ALLARME INGRASSAGGIO GUIDE - Mancata commutazione sensore sulla singola pompata
224=ALLARME SOFTWARE - File di configurazione utensili PATH_CONF.TXT non trovato
225=ALLARME SOFTWARE - Errore in apertura / lettura file CONFIG.PAR
226=ALLARME SOFTWARE - Errore in apertura / lettura file TOOLS.TXT
227=ALLARME SOFTWARE - Errore in apertura / lettura file HEADS.TXT
228=ALLARME SOFTWARE - Utensile non trovato, errato o nullo
229=ALLARME SOFTWARE - Errore in apertura / lettura file PARAM.PAR
230=ALLARME SOFTWARE - Errore di comunicazione con SW Hardlock
231=ALLARME SOFTWARE - Apertura File Errata : Variable.txt
232=ALLARME SOFTWARE - Chiusura File Errata : Variable.txt
233=ALLARME SOFTWARE - Allarme manca driver
234=ALLARME SOFTWARE - Configurazione macchina sbagliata
235=ALLARME SOFTWARE - Valore oltre soglie in controlli Routine ISO CNC
236=ALLARME SOFTWARE - Tabella Utensili non caricata (eseguire M209)
237=ALLARME SOFTWARE - Allarme movimento assi X - Y - Z
243=ALLARME MORSE - Morsa 10 non in posizione
244=ALLARME MORSE - Morsa 11 non in posizione
245=ALLARME MORSE - Morsa 12 non in posizione
246=ALLARME MORSE - Morsa 13 non in posizione
247=ALLARME MORSE - Morsa 14 non in posizione
248=ALLARME MORSE - Morsa 15 non in posizione
252=ALLARME MORSE - Micro morsa perso durante posizionamento
253=ALLARME MORSE - Micro morsa Asse X non trovato in controllo posizione
256=ALLARME GENERALE - Errore caricamento ISOMG in memoria
257=ALLARME GENERALE - Timeout caricamento ISOMG in memoria
260=ALLARME CAN OPEN - Comunicazione CanOpen in anomalia
270=ALLARME RIPARI - Riparo laterale o tunnel SX non chiuso
271=ALLARME RIPARI - Riparo laterale o tunnel DX non chiuso
272=ALLARME RIPARI - Time Out Riparo anteriore non chiuso : controlla il sensore
273=ALLARME RIPARI - Time Out Riparo anteriore non chiuso : controlla la EV
274=ALLARME RIPARI - Time Out Riparo anteriore non aperto : controlla il sensore
275=ALLARME RIPARI - Time Out Riparo anteriore non aperto : controlla la EV
276=ALLARME RIPARI - Disfunzione finecorsa riparo anteriore
282=ALLARME RIPARI - Riparo posteriore SX non Chiuso
283=ALLARME RIPARI - Riparo posteriore DX non Chiuso
286=ALLARME RIPARI - Centralina di sicurezza non attiva con riparo chiuso
298=ALLARME RIPARI - Bordo sensibile ripari intervenuto
320=ALLARME TRASCINATORE MORSE - Trasc.Morse Asse X non inserito: controlla il sensore
321=ALLARME TRASCINATORE MORSE - Trasc.Morse Asse X non inserito: controlla la EV
322=ALLARME TRASCINATORE MORSE - Trasc.Morse Asse X non disinserito: controlla il sensore
323=ALLARME TRASCINATORE MORSE - Trasc.Morse Asse X non disinserito: controlla la EV
324=ALLARME TRASCINATORE MORSE - Disfunzione Finecorsa Trasc.Morse Asse X
342=ALLARME RILEVAMENTO MORSE - Time out inserzione rilevamento morse
343=ALLARME RILEVAMENTO MORSE - Time out disinserzione rilevamento morse
371=ALLARME MORSE - Alta pressione non attiva su morsa 10
372=ALLARME MORSE - Alta pressione non attiva su morsa 11
373=ALLARME MORSE - Alta pressione non attiva su morsa 12
374=ALLARME MORSE - Alta pressione non attiva su morsa 13
375=ALLARME MORSE - Alta pressione non attiva su morsa 14
376=ALLARME MORSE - Alta pressione non attiva su morsa 15
384=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla il sensore
385=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla la EV
386=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla il sensore
387=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla la EV
388=ALLARME RIPARI - Disfunzione finecorsa visiera bassa
394=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla il sensore
395=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla la EV
396=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla il sensore
397=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla la EV
402=ALLARME UTENSILI - Utensile T1 rotto
403=ALLARME UTENSILI - Utensile T2 rotto
404=ALLARME UTENSILI - Utensile T3 rotto
405=ALLARME UTENSILI - Utensile T4 rotto
406=ALLARME UTENSILI - Utensile T5 rotto
407=ALLARME UTENSILI - Utensile T6 rotto
408=ALLARME UTENSILI - Utensile T7 rotto
409=ALLARME UTENSILI - Utensile T8 rotto
410=ALLARME UTENSILI - Utensile T9 rotto
411=ALLARME UTENSILI - Utensile T10 rotto
412=ALLARME UTENSILI - Utensile T11 rotto
413=ALLARME UTENSILI - Utensile T12 rotto
414=ALLARME UTENSILI - Drill not alive
416=ALLARME GANTRY - Morse non agganciate in gantry
417=ALLARME GANTRY - Morse non sganciate in gantry
418=ALLARME ASSI MORSE - Posizioni assi morse non congruenti (posizioni encoder perse)
419=ALLARME CAMBIO UTENSILI - Incongruenza tra utensile teoricamente presente e sensore di presenza utensile
420=ALLARME CONTROLLO UTENSILE - Utensile rotto
421=ALLARME CONTROLLO UTENSILE - Dispositivo verifica integrità utensile non funzionante
438=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa positivo
439=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa negativo
440=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa positivo
441=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa negativo
442=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa positivo
443=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa negativo
444=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa positivo
445=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa negativo
446=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa positivo
447=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa negativo
448=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa positivo
449=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa negativo
475=ALLARME CONFIGURAZIONE - Errore inizializzazione variabili PLC
476=ALLARME CONFIGURAZIONE - Errore lettura confmac
477=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (MGPilot)
478=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (REM_CTRL)
480=ALLARME ASSE X - Livello Batteria encoder basso
481=ALLARME ASSE Y - Livello Batteria encoder basso
482=ALLARME ASSE Z - Livello Batteria encoder basso
483=ALLARME ASSE A - Livello Batteria encoder basso
484=ALLARME ASSE W - Livello Batteria encoder basso
487=ALLARME ASSE X - Livello Batteria encoder basso e posizione assoluta persa
488=ALLARME ASSE Y - Livello Batteria encoder basso e posizione assoluta persa
489=ALLARME ASSE Z - Livello Batteria encoder basso e posizione assoluta persa
490=ALLARME ASSE A - Livello Batteria encoder basso e posizione assoluta persa
491=ALLARME ASSE W - Livello Batteria encoder basso e posizione assoluta persa
496=ALLARME ASSE X - Overflow sui giri massimi del multiturn dell'encoder assoluto
497=ALLARME ASSE Y - Overflow sui giri massimi del multiturn dell'encoder assoluto
498=ALLARME ASSE Z - Overflow sui giri massimi del multiturn dell'encoder assoluto
499=ALLARME ASSE A - Overflow sui giri massimi del multiturn dell'encoder assoluto
500=ALLARME ASSE W - Overflow sui giri massimi del multiturn dell'encoder assoluto
503=ALLARME ASSE X - Posizione assoluta encoder non inizializzata
504=ALLARME ASSE Y - Posizione assoluta encoder non inizializzata
505=ALLARME ASSE Z - Posizione assoluta encoder non inizializzata
506=ALLARME ASSE A - Posizione assoluta encoder non inizializzata
507=ALLARME ASSE W - Posizione assoluta encoder non inizializzata
512=ALLARME ASSE X - Funzione di reset encoder assoluto non riuscita
513=ALLARME ASSE Y - Funzione di reset encoder assoluto non riuscita
514=ALLARME ASSE Z - Funzione di reset encoder assoluto non riuscita
515=ALLARME ASSE A - Funzione di reset encoder assoluto non riuscita
516=ALLARME ASSE W - Funzione di reset encoder assoluto non riuscita
519=ALLARME ASSE X - La tensione DC del circuito principale è più bassa del valore standard
520=ALLARME ASSE Y - La tensione DC del circuito principale è più bassa del valore standard
521=ALLARME ASSE Z - La tensione DC del circuito principale è più bassa del valore standard
522=ALLARME ASSE A - La tensione DC del circuito principale è più bassa del valore standard
523=ALLARME ASSE W - La tensione DC del circuito principale è più bassa del valore standard
528=ALLARME ASSE X - Mancanza di una fase in ingresso
529=ALLARME ASSE Y - Mancanza di una fase in ingresso
530=ALLARME ASSE Z - Mancanza di una fase in ingresso
531=ALLARME ASSE A - Mancanza di una fase in ingresso
532=ALLARME ASSE W - Mancanza di una fase in ingresso
535=ALLARME ASSE X - La velocità del motore è in overshoot rispetto al valore massimo di targa
536=ALLARME ASSE Y - La velocità del motore è in overshoot rispetto al valore massimo di targa
537=ALLARME ASSE Z - La velocità del motore è in overshoot rispetto al valore massimo di targa
538=ALLARME ASSE A - La velocità del motore è in overshoot rispetto al valore massimo di targa
539=ALLARME ASSE W - La velocità del motore è in overshoot rispetto al valore massimo di targa
544=ALLARME PLC IEC - PLC IEC timeout di not alive
545=ALLARME PLC IEC - Errore di comunicazione COM con inverter 0
560=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse X
561=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Y
562=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Z
563=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse A
564=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse W

[MSG]
1=MESSAGGIO OPERATORE - Assi non riferiti
2=MESSAGGIO OPERATORE - Macchina in HOLD
3=MESSAGGIO OPERATORE - Utensile sconosciuto su mandrino
4=MESSAGGIO OPERATORE - Potenziometro a Zero in Ciclo Automatico
5=MESSAGGIO OPERATORE - Macchina in HOLD da Magazzino
6=MESSAGGIO OPERATORE - Macchina in HOLD da Morse Zona SX
7=MESSAGGIO OPERATORE - Macchina in HOLD da Morse Zona DX
8=MESSAGGIO OPERATORE - Macchina in HOLD da Mandrino
9=MESSAGGIO OPERATORE - Macchina in HOLD da Ripari
10=MESSAGGIO OPERATORE - Magazzino in potenziale collisione con carter laterale SX della macchina
11=MESSAGGIO OPERATORE - Mandrino in potenziale collisione con magazzino
12=MESSAGGIO OPERATORE - Blocco Esecuzioni FATM Attivo
13=MESSAGGIO OPERATORE - Hold apertura / chiusura ripari anteriori da posizione assi Y, A, C
14=MESSAGGIO OPERATORE - Attenzione : Possibile corto sugli ingressi non ritentivi
15=MESSAGGIO OPERATORE - Potenziale collisione fra utensile e riparo anteriore
16=MESSAGGIO OPERATORE - Sbloc. Ut. diretto possibile solo con ripari bassi
25=MESSAGGIO OPERATORE - Ingrassaggio Automatico disabilitato
27=MESSAGGIO OPERATORE - Assenza uscite pericolose con centralina di sicurezza ok
30=MESSAGGIO OPERATORE - Inizializzazione password Bridge fatta, riavviare
31=MESSAGGIO OPERATORE - Errore scrittura file contatori
77=MESSAGGIO OPERATORE - Errore caricamento funzioni manuali (MGPilot)
78=MESSAGGIO OPERATORE - Errore caricamento funzioni manuali (REM_CTRL)
80=MESSAGGIO OPERATORE - Motore asse X in preallarme da sovraccarico
81=MESSAGGIO OPERATORE - Motore asse Y in preallarme da sovraccarico
82=MESSAGGIO OPERATORE - Motore asse Z in preallarme da sovraccarico
83=MESSAGGIO OPERATORE - Motore asse A in preallarme da sovraccarico
84=MESSAGGIO OPERATORE - Motore asse W in preallarme da sovraccarico
88=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso e posizione assoluta persa
89=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso e posizione assoluta persa
90=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso e posizione assoluta persa
91=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso e posizione assoluta persa
92=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso e posizione assoluta persa
96=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso
97=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso
98=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso
99=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso
100=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso
104=MESSAGGIO OPERATORE - Posizione assoluta encoder asse X non inizializzata
105=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Y non inizializzata
106=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Z non inizializzata
107=MESSAGGIO OPERATORE - Posizione assoluta encoder asse A non inizializzata
108=MESSAGGIO OPERATORE - Posizione assoluta encoder asse W non inizializzata
112=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse X
113=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Y
114=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Z
115=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse A
116=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse W
