A          B ATTIVA 
A APRI     B CHIUDI 
A JOG -    B JOG + 
A DEPOSITO B PRELIEV 
A DISINS.  B INSERIM 
A INDIETRO B AVANTI 
A ROT.ORA. B ROT.ANT 
A FINE     B INIZIO 
A BLOCCA   B SBLOCCA 
A SX       B DX 
