[ALARM]
1=ALARM X-ACHSE - Stoerung des Antriebs der X-Achse
2=ALARM Y-ACHSE - Stoerung des Antriebs der Y-Achse
3=ALARM Z-ACHSE - Stoerung des Antriebs der Z-Achse
4=ALARM B-ACHSE - Stoerung des Antriebs der B-Achse
5=ALARM C-ACHSE - Stoerung des Antriebs der C-Achse
6=ALARM W-ACHSE - Stoerung des Antriebs der W-Achse
9=GENERAL ALARM - Keine Macht zu den Axt-Antrieben
15=SOFTWARE ALARM - Alarm counter read writing
19=AL. SPANNEINRICHTUNGSACHSE M10 - Stoer. Antrieb Spanneinrichtungsachse M10
20=AL. SPANNEINRICHTUNGSACHSE M11 - Stoer. Antrieb Spanneinrichtungsachse M11
21=AL. SPANNEINRICHTUNGSACHSE M12 - Stoer. Antrieb Spanneinrichtungsachse M12
22=AL. SPANNEINRICHTUNGSACHSE M13 - Stoer. Antrieb Spanneinrichtungsachse M13
23=AL. SPANNEINRICHTUNGSACHSE M14 - Stoer. Antrieb Spanneinrichtungsachse M14
24=AL. SPANNEINRICHTUNGSACHSE M15 - Stoer. Antrieb Spanneinrichtungsachse M15
32=ALLGEMEINER ALARM - Spannungsversorgung ausgefallen
33=ALLGEMEINER ALARM - Not-Aus gedrueckt
34=ALLGEMEINER ALARM - Hilfsstromkreise nicht eingeschaltet
35=ALLGEMEINER ALARM- Luftdruck unzureichend
36=ALLGEMEINER ALARM - Temperatur im Schaltschrank nicht ok
37=ALLGEMEINER ALARM - Schutzschalter ausgeloest
39=ALARM SPAENEFOERDERER - Schutzschalter Foerderer ausgeloest
40=ALARM ABSAUGER - Schutzschalter Absauger ausgeloest
42=ALLGEMEINER ALARM - CNC auf Alarm
43=ALLGEMEINER ALARM - CNC1 auf Alarm
44=ALLGEMEINER ALARM - CNC2 auf Alarm
46=ALLGEMEINER ALARM - Not all CNC0, CNC1, CNC2 in manual mode
47=ALLGEMEINER ALARM - Not all CNC0, CNC1, CNC2 in automatic mode
48=ALARM SPINDEL - Frequenzumrichter der Spindel defekt
49=ALARM SPINDEL - Frequenzumrichter der Spindel ueberlastet
50=ALARM SPINDEL - Spindel rotiert nicht
51=ALARM SPINDEL - Spindel dreht nicht mit Nenndrehzahl
52=ALARM SPINDEL - Timeout Werkzeugklemmung loesen
53=ALARM SPINDEL - Timeout Werkzeugklemmung
54=ALARM SPINDEL - Stoerung Endschalter Werkzeugklemmung
55=ALARM SPINDEL - Werkzeug nicht korrekt gespannt
56=ALARM SPINDEL - Unbekanntes Werkzeug in der Spindel
57=SPINDLE ALARM - Overload Relay Tripped Module Spindle Cooling
58=ALARM SPINDEL - Durchflussbegrenzer Spindel-Fluessigkeitskuehler auf Alarm
62=ALARM SPINDEL - Ubermaßige Vibrationen an der Spindel
63=ALARM SPINDEL - Ubertemperatur an der Spindel
64=ALARME ACHSEN - X-Achse in pos. Richtung ausserhalb Verfahrbereich
65=ALARME ACHSEN - X-Achse in neg. Richtung ausserhalb Verfahrbereich
66=ALARME ACHSEN - Y-Achse in pos. Richtung ausserhalb Verfahrbereich
67=ALARME ACHSEN - Y-Achse in neg. Richtung ausserhalb Verfahrbereich
68=ALARME ACHSEN - Z-Achse in pos. Richtung ausserhalb Verfahrbereich
69=ALARME ACHSEN - Z-Achse in neg. Richtung ausserhalb Verfahrbereich
70=ALARME ACHSEN - B-Achse in pos. Richtung ausserhalb Verfahrbereich
71=ALARME ACHSEN - B-Achse in neg. Richtung ausserhalb Verfahrbereich
72=ALARME ACHSEN - C-Achse in pos. Richtung ausserhalb Verfahrbereich
73=ALARME ACHSEN - C-Achse in neg. Richtung ausserhalb Verfahrbereich
74=ALARME ACHSEN - P-Achse in pos. Richtung ausserhalb Verfahrbereich
75=ALARME ACHSEN - P-Achse in neg. Richtung ausserhalb Verfahrbereich
76=ALARME ACHSEN - H-Achse in pos. Richtung ausserhalb Verfahrbereich
77=ALARME ACHSEN - H-Achse in neg. Richtung ausserhalb Verfahrbereich
78=ALARME ACHSEN - W-Achse in pos. Richtung ausserhalb Verfahrbereich
79=ALARME ACHSEN - W-Achse in neg. Richtung ausserhalb Verfahrbereich
80=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 1 nicht moeglich
81=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 1 nicht moeglich
82=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 2 nicht moeglich
83=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 2 nicht moeglich
84=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 3 nicht moeglich
85=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 3 nicht moeglich
86=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 4 nicht moeglich
87=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 4 nicht moeglich
88=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 5 nicht moeglich
89=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 5 nicht moeglich
90=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 6 nicht moeglich
91=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 6 nicht moeglich
92=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 7 nicht moeglich
93=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 7 nicht moeglich
94=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 8 nicht moeglich
95=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 8 nicht moeglich
96=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 9 nicht moeglich
97=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 9 nicht moeglich
98=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 10 nicht moeglich
99=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 10 nicht moeglich
100=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 11 nicht moeglich
101=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 11 nicht moeglich
102=ALARM WERKZEUGWECHSEL - Ablage Werkzeug 12 nicht moeglich
103=ALARM WERKZEUGWECHSEL - Entnahme Werkzeug 12 nicht moeglich
104=TOOL MAGAZINE ALARM - Tool magazine hook not disengagement
105=ALARM WERKZEUGMAGAZIN - Zyklusbeginn mit Spindel in potentieller Kollision mit Magazin 
106=TOOL MAGAZINE ALARM - Tool magazine hook not out encumbrance
107=ALARM SPANNEINRICHTUNGEN - Hochdruck ohne Befehl eingeschaltet
108=ALARME ACHSEN - Mogliche Kollision zwischen Werkzeug und Frontschutz
115=ALARM SPANNEINRICHTUNGEN - Spannbock 10 nicht korrekt positioniert
116=ALARM SPANNEINRICHTUNGEN - Spannbock 11 nicht korrekt positioniert
117=ALARM SPANNEINRICHTUNGEN - Spannbock 12 nicht korrekt positioniert
118=ALARM SPANNEINRICHTUNGEN - Spannbock 13 nicht korrekt positioniert
119=ALARM SPANNEINRICHTUNGEN - Spannbock 14 nicht korrekt positioniert
120=ALARM SPANNEINRICHTUNGEN - Spannbock 15 nicht korrekt positioniert
124=ALARM SPANNEINRICHTUNGEN - Falsche Anzahl der Spanneinrichtungen
125=AL. SPANNEINR. - Fehl. Pos. Spanneinr. durch PC: Werte ausser zul. Bereich
136=VICES ALARM - Motorized vices power supply not OK
138=PRECISION BARRIER ALARM - Barrier not eingaged
139=PRECISION BARRIER ALARM - Barrier not diseingaged
140=PRECISION BARRIER ALARM - Wrong position at zero
141=PRECISION BARRIER ALARM - Wrong probing index
142=PRECISION BARRIER ALARM - Piece not found
143=POSITIONING ALARM - Piece badly placed at barrier
154=BARRIER ALARM - DX4 Barrier not in X4R position
155=BARRIER ALARM - Faulty limit switches DX4 barrier
156=BARRIER ALARM - SX1 Barrier not in X1L position
157=BARRIER ALARM - DX4 Barrier not in X3R position
158=BARRIER ALARM - DX4 Barrier not in X2R position
159=BARRIER ALARM - DX4 Barrier not in X1R position
160=ALARM ANSCHLAEGE - Anschlag links 1 nicht oben
161=ALARM ANSCHLAEGE - Anschlag links 1 nicht unten
166=ALARM ANSCHLAEGE - Anschlag rechts 4 nicht oben
167=ALARM ANSCHLAEGE - Anschlag rechts 4 nicht unten
176=ALARM TISCHE - Tisch nicht vorn: Sensor pruefen
177=ALARM TISCHE - Tisch nicht vorn: MV pruefen
178=ALARM TISCHE - Tisch nicht hinten: Sensor pruefen
179=ALARM TISCHE - Tisch nicht hinten: MV pruefen
180=ALARM TISCHE - Stoerung Endschalter Tisch
198=ALARM LUBRICA - Niedriger Fuellstand fuer normales Schmiermittel
199=LUBRICA ALARM - High Normal Lubrica level
200=ALARM TASTER MARPOSS - Taster bereits am Anschlag am Beginn des Tastvorgangs
201=ALARM TASTER MARPOSS - Werkstuck vom Taster nicht erkannt
202=ALARM TASTER MARPOSS - Fehler Index Taster
203=ALARM TASTER MARPOSS - Marposs Taster in Storung
204=ALARM TASTER MARPOSS - Batterie leer Marposs Taster
205=ALARM TASTER MARPOSS - Taster noch am Anschlag nach Beendigung des Abtastvorgangs
206=ALARM TASTER MARPOSS - Correction values too big: verify probe
212=Alarm Schmierung der Führung - Fett niederes Niveau
213=Alarm Schmierung der Führung - Fehlfunktion der Pumpe/Ventil
214=Alarm Schmierung der Führung - Ausführung gestoppt Überschreitung Arbeitszeit
215=Alarm Schmierung der Führung - Fehlende Sensor auf der einzelnen Pumpe
224=ALARM SOFTWARE - Fehler beim Oeffnen/Schliessen von Datei: Path_conf.Txt
225=ALARM SOFTWARE - Fehler beim Oeffnen von Datei: Config.par
226=ALARM SOFTWARE - Fehler beim Oeffnen von Datei: Tools.txt
227=ALARM SOFTWARE - Fehler beim Oeffnen von Datei: Heads.txt
228=ALARM SOFTWARE - Fehler beim Werkzeugaufruf 
229=ALARM SOFTWARE - Fehler Schliessen v. Datei: Config.Par/Tools.txt/Heads.txt 
230=ALARM SOFTWARE - Fehler beim Lesen der Datei
231=ALARM SOFTWARE - Fehler beim Oeffnen von Datei: Variable.txt
232=ALARM SOFTWARE - Fehler Schliessen v. Datei: Variable.txt
233=ALARM SOFTWARE - Alarm Treiber nicht vorhanden
234=ALARM SOFTWARE - Maschinenkonfiguration falsch 
235=ALARM SOFTWARE - Endlage ueberschritten bei Kontrollen Routine ISO NC
236=ALARM SOFTWARE - Werkzeugtabelle nicht geladen (M209 ausfuhren)
237=ALARM SOFTWARE - Alarm Bewegung Achsen X - Y - Z 
243=ALARM SPANNEINRICHTUNGEN - Spannbock 10 nicht positioniert
244=ALARM SPANNEINRICHTUNGEN - Spannbock 11 nicht positioniert
245=ALARM SPANNEINRICHTUNGEN - Spannbock 12 nicht positioniert
246=ALARM SPANNEINRICHTUNGEN - Spannbock 13 nicht positioniert
247=ALARM SPANNEINRICHTUNGEN - Spannbock 14 nicht positioniert
248=ALARM SPANNEINRICHTUNGEN - Spannbock 15 nicht positioniert
252=ALARM SPANNEINR. - Mikroschalter Spannbock bei Positionierung verloren
253=AL. SPANNEINR. - Mikrosch. Spanneinr. X-Achse b. Positionskontr. nicht gef.
256=GENERAL ALARM - Error load ISOMG in memory
257=GENERAL ALARM - Timeout loading ISOMG in memory
260=ALARM CAN OPEN - Fehler Kommunikation CanOpen
270=SIDEGUARD ALARM - Side Guard or tunnel LH not closed
271=SIDEGUARD ALARM - Side Guard or tunnel RH not closed
272=ALARM SCHUTZTUEREN - Timeout vord. Schutztuer nicht geschl.: Sensor pruef.
273=ALARM SCHUTZTUEREN - Timeout vord. Schutztuer nicht geschl.: MV pruefen
274=ALARM SCHUTZTUEREN - Timeout vord. Schutztuer nicht offen: Sensor pruef.
275=ALARM SCHUTZTUEREN - Timeout vord. Schutztuer nicht offen: MV pruefen
276=ALARM SCHUTZTUEREN - Stoerung Endschalter vordere Schutztuer 
282=ALARM SCHUTZTUEREN - Linke hintere Schutztuer nicht geschlossen
283=ALARM SCHUTZTUEREN - Rechte hintere Schutztuer nicht geschlossen
286=ALARM SCHUTZTUEREN - Sicherheitselektronik bei geschl. Schutztuer aus
298=FRONTGUARD ALARM - Guard sensitive edge triggered
320=AL. SPANNBOCKMITN. - Spannbockmitn. X-Achse nicht eingesetzt: Sensor pruef.
321=AL. SPANNBOCKMITN. - Spannbockmitn. X-Achse nicht eingesetzt: MV pruefen
322=AL. SPANNBOCKMITN. - Spannbockmitn. X-Achse nicht ausgekuppelt: Sensor pruef.
323=AL. SPANNBOCKMITN. - Spannbockmitn. X-Achse nicht ausgekuppelt: MV pruefen
324=ALARM SPANNBOCKMITNEHMER - Stoerung Endschalter Spannbockmitn. X-Achse
342=CLAMP DETECTION ALARM - Clamp detection engagement timeout 
343=CLAMP DETECTION ALARM - Clamp detection disengagement timeout 
371=VICES ALARM - High Pressure Vice 10 not active
372=VICES ALARM - High Pressure Vice 11 not active
373=VICES ALARM - High Pressure Vice 12 not active
374=VICES ALARM - High Pressure Vice 13 not active
375=VICES ALARM - High Pressure Vice 14 not active
376=VICES ALARM - High Pressure Vice 15 not active
384=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the sensor
385=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the EV
386=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
387=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
388=GUARD ALARM - Faulty limit switches Down Guard
394=GUARD ALARM - Time Out Up Guard not open (down movement) : check the sensor
395=GUARD ALARM - Time Out Up Guard not open (down movement) : check the EV
396=GUARD ALARM - Time Out Up Guard not close (up movement) : check the sensor
397=GUARD ALARM - Time Out Up Guard not close (up movement) : check the EV
402=TOOL ALARM - Tool T1 broken
403=TOOL ALARM - Tool T2 broken
404=TOOL ALARM - Tool T3 broken
405=TOOL ALARM - Tool T4 broken
406=TOOL ALARM - Tool T5 broken
407=TOOL ALARM - Tool T6 broken
408=TOOL ALARM - Tool T7 broken
409=TOOL ALARM - Tool T8 broken
410=TOOL ALARM - Tool T9 broken
411=TOOL ALARM - Tool T10 broken
412=TOOL ALARM - Tool T11 broken
413=TOOL ALARM - Tool T12 broken
414=TOOL ALARM - Drill not alive
416=GANTRY ALARM - Clamps not engaged in gantry
417=GANTRY ALARM - Clamps not released from gantry
418=VICES AXES ALARM - Vices axes positions not congruent (lost encoder positions)
419=ALARM WERKZEUGWECHSEL - Inkongruenz zwichen theoretisch vorhandenem werkzeug und sensor fur werkzeug vorhanden
420=WERKZEUGPRÜFUNG ALARM - Gebrochenes Werkzeug
421=WERKZEUGPRUFUNG ALARM - Gerat zur Uberprufung der Werkzeugintegritat funktioniert nicht
438=VICE AXIS ALARM - Vice axis M10 in Positive Overtravel
439=VICE AXIS ALARM - Vice axis M10 in Negative Overtravel
440=VICE AXIS ALARM - Vice axis M11 in Positive Overtravel
441=VICE AXIS ALARM - Vice axis M11 in Negative Overtravel
442=VICE AXIS ALARM - Vice axis M12 in Positive Overtravel
443=VICE AXIS ALARM - Vice axis M12 in Negative Overtravel
444=VICE AXIS ALARM - Vice axis M13 in Positive Overtravel
445=VICE AXIS ALARM - Vice axis M13 in Negative Overtravel
446=VICE AXIS ALARM - Vice axis M14 in Positive Overtravel
447=VICE AXIS ALARM - Vice axis M14 in Negative Overtravel
448=VICE AXIS ALARM - Vice axis M15 in Positive Overtravel
449=VICE AXIS ALARM - Vice axis M15 in Negative Overtravel
475=CONFIGURATION ALARM - Initialization variables PLC error
476=CONFIGURATION ALARM - Error reading CONFMAC file
477=CONFIGURATION ALARM - Error loading manual function (MGPilot)
478=CONFIGURATION ALARM - Error loading manual function (REM_CTRL)
480=ALARM AXIS X - Voltage level low encoder battery
481=ALARM AXIS Y - Voltage level low encoder battery
482=ALARM AXIS Z - Voltage level low encoder battery
483=ALARM AXIS A - Voltage level low encoder battery
484=ALARM AXIS W - Voltage level low encoder battery
487=ALARM AXIS X - Voltage level low encoder battery and absolute position lost
488=ALARM AXIS Y - Voltage level low encoder battery and absolute position lost
489=ALARM AXIS Z - Voltage level low encoder battery and absolute position lost
490=ALARM AXIS A - Voltage level low encoder battery and absolute position lost
491=ALARM AXIS W - Voltage level low encoder battery and absolute position lost
496=ALARM AXIS X - Overflow on the maximum revolutions of the absolute multiturn encoder
497=ALARM AXIS Y - Overflow on the maximum revolutions of the absolute multiturn encoder
498=ALARM AXIS Z - Overflow on the maximum revolutions of the absolute multiturn encoder
499=ALARM AXIS A - Overflow on the maximum revolutions of the absolute multiturn encoder
500=ALARM AXIS W - Overflow on the maximum revolutions of the absolute multiturn encoder
503=ALARM AXIS X - Absolute encoder position not initialized
504=ALARM AXIS Y - Absolute encoder position not initialized
505=ALARM AXIS Z - Absolute encoder position not initialized
506=ALARM AXIS A - Absolute encoder position not initialized
507=ALARM AXIS W - Absolute encoder position not initialized
512=ALARM AXIS X - Absolute encoder reset function failed
513=ALARM AXIS Y - Absolute encoder reset function failed
514=ALARM AXIS Z - Absolute encoder reset function failed
515=ALARM AXIS A - Absolute encoder reset function failed
516=ALARM AXIS W - Absolute encoder reset function failed
519=ALARM AXIS X - Main circuit DC voltage is lower than standard value
520=ALARM AXIS Y - Main circuit DC voltage is lower than standard value
521=ALARM AXIS Z - Main circuit DC voltage is lower than standard value
522=ALARM AXIS A - Main circuit DC voltage is lower than standard value
523=ALARM AXIS W - Main circuit DC voltage is lower than standard value
528=ALARM AXIS X - Lack of an input phase
529=ALARM AXIS Y - Lack of an input phase
530=ALARM AXIS Z - Lack of an input phase
531=ALARM AXIS A - Lack of an input phase
532=ALARM AXIS W - Lack of an input phase
535=ALARM AXIS X - Motor speed is in overshoot compared to maximum value
536=ALARM AXIS Y - Motor speed is in overshoot compared to maximum value
537=ALARM AXIS Z - Motor speed is in overshoot compared to maximum value
538=ALARM AXIS A - Motor speed is in overshoot compared to maximum value
539=ALARM AXIS W - Motor speed is in overshoot compared to maximum value
544=ALARM PLC IEC - Timeout PLC IEC not alive
545=ALARM PLC IEC - COM communication error with inverter 0
560=ALARM PLC IEC - COM communication error with drive axis X
561=ALARM PLC IEC - COM communication error with drive axis Y
562=ALARM PLC IEC - COM communication error with drive axis Z
563=ALARM PLC IEC - COM communication error with drive axis A
564=ALARM PLC IEC - COM communication error with drive axis W

[MSG]
1=BETRIEBSMELDUNG - Referenzpunkte der Achsen nicht angefahren
2=BETRIEBSMELDUNG - Maschine auf HOLD
3=BETRIEBSMELDUNG - Unbekanntes Werkzeug in der Spindel
4=BETRIEBSMELDUNG - Potentiometer auf Null in Automatikzyklus
5=BETRIEBSMELDUNG - Maschine auf HOLD ausgeloest durch WZ-Magazin
6=BETRIEBSMELDUNG - Maschine auf HOLD, ausgeloest durch Spanneinr. linke Zone
7=BETRIEBSMELDUNG - Maschine auf HOLD, ausgeloest durch Spanneinr. rechte Zone
8=BETRIEBSMELDUNG - Maschine auf Hold ausgeloest durch Spindel
9=BETRIEBSMELDUNG - Maschine auf HOLD, ausgeloest durch Schutztueren
10=OPERATOR MESSAGE - Tool magazine in potential collision with left side cover of the machine  
11=BETRIEBSMELDUNG - Spindel in potentieller Kollision mit Magazin
12=BETRIEBSMELDUNG - Sperre FATM-Ausfuehrung eingeschaltet
13=BETRIEBSMELDUNG - Hold opening / closing Front Guard from Y, B, C axes position
14=BETRIEBSMELDUNG - Achtung: moegl. Kurzschl. auf Eing. o. Selbsthaltefunktion
15=OPERATOR MESSAGE - Potential collision between tool and front guard
16=BETRIEBSMELDUNG - Dir. Werkzeugfreigabe nur bei Schutztueren unten moeglich
25=BETRIEBSMELDUNG - Automatische Schmierung abgeschaltet
27=OPERATOR MESSAGE - No security common outputs with safety switch on
30=OPERATOR MESSAGE - Bridge password initialization done, restart
31=OPERATOR MESSAGE - Counters file writing error
77=OPERATOR MESSAGE - loading manual functions Error (MG Pilot)
78=OPERATOR MESSAGE - loading manual functions Error (REM_CTRL)
80=OPERATOR MESSAGE - X axis motor in overload prealarm
81=OPERATOR MESSAGE - Y axis motor in overload prealarm
82=OPERATOR MESSAGE - Z axis motor in overload prealarm
83=OPERATOR MESSAGE - A axis motor in overload prealarm
84=OPERATOR MESSAGE - W axis motor in overload prealarm
88=OPERATOR MESSAGE - Voltage level low X axis encoder battery and absolute position lost
89=OPERATOR MESSAGE - Voltage level low Y axis encoder battery and absolute position lost
90=OPERATOR MESSAGE - Voltage level low Z axis encoder battery and absolute position lost
91=OPERATOR MESSAGE - Voltage level low A axis encoder battery and absolute position lost
92=OPERATOR MESSAGE - Voltage level low W axis encoder battery and absolute position lost
96=OPERATOR MESSAGE - Voltage level low X axis encoder battery
97=OPERATOR MESSAGE - Voltage level low Y axis encoder battery
98=OPERATOR MESSAGE - Voltage level low Z axis encoder battery
99=OPERATOR MESSAGE - Voltage level low A axis encoder battery
100=OPERATOR MESSAGE - Voltage level low W axis encoder battery
104=OPERATOR MESSAGE - X axis absolute encoder position not initialized
105=OPERATOR MESSAGE - Y axis absolute encoder position not initialized
106=OPERATOR MESSAGE - Z axis absolute encoder position not initialized
107=OPERATOR MESSAGE - A axis absolute encoder position not initialized
108=OPERATOR MESSAGE - W axis absolute encoder position not initialized
112=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn X axis encoder
113=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Y axis encoder
114=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Z axis encoder
115=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn A axis encoder
116=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn W axis encoder
