A          B ENABLE 
A OPEN     B CLOSE 
A JOG -    B JOG + 
A UNLOAD   B LOAD 
A REMOVE   B INSERT 
A BACKWARD B FORWARD 
A ROT.CLK. B ROT.ANT 
A END      B START 
A BLOCK    B UNBLOCK 
A LH       B RH 
