[ALARM]
1=ALARME AXE X - Anomalie actionnement axe X
2=ALARME AXE Y - Anomalie actionnement axe Y
3=ALARME AXE Z - Anomalie actionnement axe Z
4=ALARME AXE B - Anomalie actionnement axe B
5=ALARME AXE C - Anomalie actionnement axe C
6=ALARME AXE W - Anomalie actionnement axe W
9=GÉNÉRAL ALARM - Aucun pouvoir des actionnement Axes
15=ALARME SOFTWARE - Alarm counter read writing
19=ALARME AXE ÉTAU M10 - Anomalie actionnement axe étau M10
20=ALARME AXE ÉTAU M11 - Anomalie actionnement axe étau M11
21=ALARME AXE ÉTAU M12 - Anomalie actionnement axe étau M12
22=ALARME AXE ÉTAU M13 - Anomalie actionnement axe étau M13
23=ALARME AXE ÉTAU M14 - Anomalie actionnement axe étau M14
24=ALARME AXE ÉTAU M15 - Anomalie actionnement axe étau M15
32=ALARME GÉNÉRALE  - Absence alimentations
33=ALARME GÉNÉRALE - Bouton d’urgence enclenché
34=ALARME GÉNÉRALE - Auxiliaires désactivés
35=ALARME GÉNÉRALE - Pression air insuffisante
36=ALARME GÉNÉRALE - Température armoire anormale
37=ALARME GÉNÉRALE - Déclenchement Disjoncteurs
39=ALARME CONVOYEUR COPEAUX - Protection thermique convoyeur  déclenchée
40=ALARME ASPIRATEUR - Protection thermique aspirateur déclenchée
42=ALARME GÉNÉRALE - CNC en alarme
43=ALARME GÉNÉRALE - CNC1 en alarme
44=ALARME GÉNÉRALE - CNC2 en alarme
46=ALARME GÉNÉRALE - Not all CNC0, CNC1, CNC2 in manual mode
47=ALARME GÉNÉRALE - Not all CNC0, CNC1, CNC2 in automatic mode
48=ALARME BROCHE - Anomalie onduleur broche
49=ALARME BROCHE - Surcharge onduleur broche
50=ALARME BROCHE - Absence de rotation broche
51=ALARME BROCHE - Vitesse pas à plein régime
52=ALARME BROCHE - Time out déblocage outil
53=ALARME BROCHE - Time out blocage outil
54=ALARME BROCHE - Anomalie fin de course blocage outil
55=ALARME BROCHE - Outil mal accroché
56=ALARME BROCHE - Outil inconnu sur broche
57=SPINDLE ALARM - Overload Relay Tripped Module Spindle Cooling
58=ALARME BROCHE - Débitmètre groupe de refroidissement broche en alarme
62=ALARME BROCHE - Vibrations excessives sur la broche
63=ALARME BROCHE - Temperature excessive sur la broche
64=ALARME AXE - Axe X hors-course positif
65=ALARME AXE - Axe X hors-course négatif
66=ALARME AXE - Axe Y hors-course positif
67=ALARME AXE - Axe Y hors-course négatif
68=ALARME AXE - Axe Z hors-course positif
69=ALARME AXE - Axe Z hors-course négatif
70=ALARME AXE - Axe B hors-course positif
71=ALARME AXE - Axe B hors-course négatif
72=ALARME AXE - Axe C hors-course positif
73=ALARME AXE - Axe C hors-course négatif
74=ALARME AXE - Axe P hors-course positif
75=ALARME AXE - Axe P hors-course négatif
76=ALARME AXE - Axe H hors-course positif
77=ALARME AXE - Axe H hors-course négatif
78=ALARME AXE - Axe W hors-course positif
79=ALARME AXE - Axe W hors-course négatif
80=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 1
81=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 1
82=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 2
83=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 2
84=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 3
85=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 3
86=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 4
87=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 4
88=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 5
89=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 5
90=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 6
91=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 6
92=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 7
93=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 7
94=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 8
95=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 8
96=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 9
97=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 9
98=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 10
99=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 10
100=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 11
101=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 11
102=ALARME CHANGEMENT OUTILS - Impossible Dépôt outil 12
103=ALARME CHANGEMENT OUTILS - Impossible prélèvement outil 12
104=TOOL MAGAZINE ALARM - Tool magazine hook not disengagement
105=ALARME MAGASIN OUTILS - Cycle commence avec broche en collision potentielle avec magasin
106=TOOL MAGAZINE ALARM - Tool magazine hook not out encumbrance
107=ALARME ÉTAUX - Haute Pression ctive sans commande
108=ALARMES AXES - Collision potentielle entre l'outil et les protections avant
115=ALARME ÉTAUX - Étau 10 mal positionné
116=ALARME ÉTAUX - Étau 11 mal positionné
117=ALARME ÉTAUX - Étau 12 mal positionné
118=ALARME ÉTAUX - Étau 13 mal positionné
119=ALARME ÉTAUX - Étau 14 mal positionné
120=ALARME ÉTAUX - Étau 15 mal positionné
124=ALARME ÉTAUX - Nombre étaux incorrect
125=ALARME ÉTAUX - Erreur pos. Étaux de PC: valeurs hors limites
136=VICES ALARM - Motorized vices power supply not OK
138=PRECISION BARRIER ALARM - Barrier not eingaged
139=PRECISION BARRIER ALARM - Barrier not diseingaged
140=PRECISION BARRIER ALARM - Wrong position at zero
141=PRECISION BARRIER ALARM - Wrong probing index
142=PRECISION BARRIER ALARM - Piece not found
143=POSITIONING ALARM - Piece badly placed at barrier
154=BARRIER ALARM - DX4 Barrier not in X4R position
155=BARRIER ALARM - Faulty limit switches DX4 barrier
156=BARRIER ALARM - SX1 Barrier not in X1L position
157=BARRIER ALARM - DX4 Barrier not in X3R position
158=BARRIER ALARM - DX4 Barrier not in X2R position
159=BARRIER ALARM - DX4 Barrier not in X1R position
160=ALARME BUTÉES - Butée GA 1 non haute
161=ALARME BUTÉES - Butée GA 1 non basse
166=ALARME BUTÉES - Butée DR 4 non haute
167=ALARME BUTÉES - Butée DR 4 non basse
176=ALARME TABLES - Table non avant : contrôler le capteur
177=ALARME TABLES - Table non avant : contrôler le capteur
178=ALARME TABLES - Table non arrière: contrôler le capteur
179=ALARME TABLES - Table non arrière: contrôler l’EV
180=ALARME TABLES - Dysfonctionnement Fin de course Table
198=ALARME LUBRICA - Niveau lubrifiant normal bas
199=LUBRICA ALARM - High Normal Lubrica level
200=ALARME PALPEUR MARPOSS - Palpeur deja en butee au debut palpation
201=ALARME PALPEUR MARPOSS - Piece non relevee par le palpeur
202=ALARME PALPEUR MARPOSS - Erreur indice palpeur
203=ALARME PALPEUR MARPOSS - Palpeur marposs en erreur
204=ALARME PALPEUR MARPOSS - Batterie dechargee palpeur Marposs
205=ALARME PALPEUR MARPOSS - Palpeur encore en butee apres fin palpage
206=ALARME PALPEUR MARPOSS - Correction values too big: verify probe
212=ALARME GRAISSAGE GUIDES - Niveau graisse bas
213=ALARME GRAISSAGE GUIDES - Anomalie pompe/electrovalve
214=ALARME GRAISSAGE GUIDES - Manque d'execution pour trop d'heures de travail
215=ALARME GRAISSAGE GUIDES - Manque de commutation du capteur sur une single pompage 
224=ALARME LOGICIEL - Ouverture\fermeture fichier erronée: Path_conf.Txt
225=ALARME LOGICIEL - Ouverture fichier erronée: config.par
226=ALARME LOGICIEL - Ouverture fichier erronée:  tools.txt
227=ALARME LOGICIEL - Ouverture fichier erronée: heads.txt
228=ALARME LOGICIEL - Erreur d’appel outil
229=ALARME LOGICIEL - Fermeture fichier erronée: config.par/tools.txt/heads.txt
230=ALARME LOGICIEL - Lecture fichier erronée 
231=ALARME LOGICIEL - Ouverture fichier erronée: variable.txt
232=ALARME LOGICIEL - Fermeture fichier erronée: variable.txt
233=ALARME LOGICIEL - Alarme absence pilote
234=ALARME LOGICIEL - Configuration machine erronée
235=ALARME LOGICIEL - Valeur hors seuil durant contrôle de routine Iso Cnc
236=ALARME LOGICIEL - Tableau outils non charge (executer M209)
237=ALARME LOGICIEL - Alarme mouvement axes X - Y - Z 
243=ALARME ÉTAUX - Positionnement incorrect étau 10
244=ALARME ÉTAUX - Positionnement incorrect étau 11
245=ALARME ÉTAUX - Positionnement incorrect étau 12
246=ALARME ÉTAUX - Positionnement incorrect étau 13
247=ALARME ÉTAUX - Positionnement incorrect étau 14
248=ALARME ÉTAUX - Positionnement incorrect étau 15
252=ALARME ÉTAUX - Micro étau perdu durant positionnement
253=ALARME ÉTAUX - Micro-contact étau Axe X non trouvé en contrôle position
256=GENERAL ALARM - Error load ISOMG in memory
257=GENERAL ALARM - Timeout loading ISOMG in memory
260=ALARME CAN OPEN - Communication anormale CanOpen
270=SIDEGUARD ALARM - Side Guard or tunnel LH not closed
271=SIDEGUARD ALARM - Side Guard or tunnel RH not closed
272=ALARME PROTECTIONS - Time out protection antérieure non fermée: contrôler le capteur
273=ALARME PROTECTIONS - Time out protection antérieure non fermée: contrôler l’EV
274=ALARME PROTECTIONS - Time out protection antérieure non ouverte: contrôler le capteur
275=ALARME PROTECTIONS - Time out protection antérieure non ouverte: contrôler l’EV.
276=ALARME PROTECTIONS - Anomalie fin de course protection antérieure
282=ALARME PROTECTIONS - Protection postérieure GAUCHE non Fermée
283=ALARME PROTECTIONS - Protection postérieure DROITE non Fermée
286=ALARME PROTECTIONS - Centrale de sécurité non active avec protection fermée
298=FRONTGUARD ALARM - Guard sensitive edge triggered
320=ALARME ENTRAÎNEMENT ÉTAUX - Entraîn. Étaux Axe X non activé: contrôler le capteur
321=ALARME ENTRAÎNEMENT ÉTAUX - Entraîn. Étaux Axe X non activé: contrôler l’EV
322=ALARME ENTRAÎNEMENT ÉTAUX - Entraîn. Étaux Axe X non désactivé: contrôler le capteur
323=ALARME ENTRAÎNEMENT ÉTAUX - Entraîn. Étaux Axe X non désactivé: contrôler l’EV
324=ALARME ENTRAÎNEMENT ÉTAUX - Dysfonctionnement Fin de course Entraîn. Étaux Axe X
342=CLAMP DETECTION ALARM - Clamp detection engagement timeout 
343=CLAMP DETECTION ALARM - Clamp detection disengagement timeout 
371=VICES ALARM - High Pressure Vice 10 not active
372=VICES ALARM - High Pressure Vice 11 not active
373=VICES ALARM - High Pressure Vice 12 not active
374=VICES ALARM - High Pressure Vice 13 not active
375=VICES ALARM - High Pressure Vice 14 not active
376=VICES ALARM - High Pressure Vice 15 not active
384=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the sensor
385=GUARD ALARM - Time Out Down Guard not open (forward movement) : check the EV
386=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
387=GUARD ALARM - Time Out Down Guard not close (backward movement) : check the sensor
388=GUARD ALARM - Faulty limit switches Down Guard
394=GUARD ALARM - Time Out Up Guard not open (down movement) : check the sensor
395=GUARD ALARM - Time Out Up Guard not open (down movement) : check the EV
396=GUARD ALARM - Time Out Up Guard not close (up movement) : check the sensor
397=GUARD ALARM - Time Out Up Guard not close (up movement) : check the EV
402=TOOL ALARM - Tool T1 broken
403=TOOL ALARM - Tool T2 broken
404=TOOL ALARM - Tool T3 broken
405=TOOL ALARM - Tool T4 broken
406=TOOL ALARM - Tool T5 broken
407=TOOL ALARM - Tool T6 broken
408=TOOL ALARM - Tool T7 broken
409=TOOL ALARM - Tool T8 broken
410=TOOL ALARM - Tool T9 broken
411=TOOL ALARM - Tool T10 broken
412=TOOL ALARM - Tool T11 broken
413=TOOL ALARM - Tool T12 broken
414=TOOL ALARM - Drill not alive
416=GANTRY ALARM - Clamps not engaged in gantry
417=GANTRY ALARM - Clamps not released from gantry
418=VICES AXES ALARM - Vices axes positions not congruent (lost encoder positions)
419=ALARME CHANGEMENT OUTILS - Incoherence entre outil theoriquement present et detecteur de presence outil
420=ALARME VERIFICATION OUTIL - Outil casse
421=ALARME VERIFICATION OUTIL - Le dispositif de verification de l'integrite de l'outil ne fonctionne pas
438=VICE AXIS ALARM - Vice axis M10 in Positive Overtravel
439=VICE AXIS ALARM - Vice axis M10 in Negative Overtravel
440=VICE AXIS ALARM - Vice axis M11 in Positive Overtravel
441=VICE AXIS ALARM - Vice axis M11 in Negative Overtravel
442=VICE AXIS ALARM - Vice axis M12 in Positive Overtravel
443=VICE AXIS ALARM - Vice axis M12 in Negative Overtravel
444=VICE AXIS ALARM - Vice axis M13 in Positive Overtravel
445=VICE AXIS ALARM - Vice axis M13 in Negative Overtravel
446=VICE AXIS ALARM - Vice axis M14 in Positive Overtravel
447=VICE AXIS ALARM - Vice axis M14 in Negative Overtravel
448=VICE AXIS ALARM - Vice axis M15 in Positive Overtravel
449=VICE AXIS ALARM - Vice axis M15 in Negative Overtravel
475=CONFIGURATION ALARM - Initialization variables PLC error
476=CONFIGURATION ALARM - Error reading CONFMAC file
477=CONFIGURATION ALARM - Error loading manual function (MGPilot)
478=CONFIGURATION ALARM - Error loading manual function (REM_CTRL)
480=ALARM AXIS X - Voltage level low encoder battery
481=ALARM AXIS Y - Voltage level low encoder battery
482=ALARM AXIS Z - Voltage level low encoder battery
483=ALARM AXIS A - Voltage level low encoder battery
484=ALARM AXIS W - Voltage level low encoder battery
487=ALARM AXIS X - Voltage level low encoder battery and absolute position lost
488=ALARM AXIS Y - Voltage level low encoder battery and absolute position lost
489=ALARM AXIS Z - Voltage level low encoder battery and absolute position lost
490=ALARM AXIS A - Voltage level low encoder battery and absolute position lost
491=ALARM AXIS W - Voltage level low encoder battery and absolute position lost
496=ALARM AXIS X - Overflow on the maximum revolutions of the absolute multiturn encoder
497=ALARM AXIS Y - Overflow on the maximum revolutions of the absolute multiturn encoder
498=ALARM AXIS Z - Overflow on the maximum revolutions of the absolute multiturn encoder
499=ALARM AXIS A - Overflow on the maximum revolutions of the absolute multiturn encoder
500=ALARM AXIS W - Overflow on the maximum revolutions of the absolute multiturn encoder
503=ALARM AXIS X - Absolute encoder position not initialized
504=ALARM AXIS Y - Absolute encoder position not initialized
505=ALARM AXIS Z - Absolute encoder position not initialized
506=ALARM AXIS A - Absolute encoder position not initialized
507=ALARM AXIS W - Absolute encoder position not initialized
512=ALARM AXIS X - Absolute encoder reset function failed
513=ALARM AXIS Y - Absolute encoder reset function failed
514=ALARM AXIS Z - Absolute encoder reset function failed
515=ALARM AXIS A - Absolute encoder reset function failed
516=ALARM AXIS W - Absolute encoder reset function failed
519=ALARM AXIS X - Main circuit DC voltage is lower than standard value
520=ALARM AXIS Y - Main circuit DC voltage is lower than standard value
521=ALARM AXIS Z - Main circuit DC voltage is lower than standard value
522=ALARM AXIS A - Main circuit DC voltage is lower than standard value
523=ALARM AXIS W - Main circuit DC voltage is lower than standard value
528=ALARM AXIS X - Lack of an input phase
529=ALARM AXIS Y - Lack of an input phase
530=ALARM AXIS Z - Lack of an input phase
531=ALARM AXIS A - Lack of an input phase
532=ALARM AXIS W - Lack of an input phase
535=ALARM AXIS X - Motor speed is in overshoot compared to maximum value
536=ALARM AXIS Y - Motor speed is in overshoot compared to maximum value
537=ALARM AXIS Z - Motor speed is in overshoot compared to maximum value
538=ALARM AXIS A - Motor speed is in overshoot compared to maximum value
539=ALARM AXIS W - Motor speed is in overshoot compared to maximum value
544=ALARM PLC IEC - Timeout PLC IEC not alive
545=ALARM PLC IEC - COM communication error with inverter 0
560=ALARM PLC IEC - COM communication error with drive axis X
561=ALARM PLC IEC - COM communication error with drive axis Y
562=ALARM PLC IEC - COM communication error with drive axis Z
563=ALARM PLC IEC - COM communication error with drive axis A
564=ALARM PLC IEC - COM communication error with drive axis W

[MSG]
1=MESSAGE OPÉRATEUR - Axes non étalonnés
2=MESSAGE OPÉRATEUR - Machine en hold
3=MESSAGE OPÉRATEUR - Outil inconnu sur la broche
4=MESSAGE OPÉRATEUR - Potentiomètre sur Zéro en Cycle Automatique
5=MESSAGE OPÉRATEUR - Machine en HOLD causée par Magasin
6=MESSAGE OPÉRATEUR - Machine en HOLD de Étaux Zone GAUCHE
7=MESSAGE OPÉRATEUR - Machine en HOLD de Étaux Zone DROITE
8=MESSAGE OPÉRATEUR - Machine en HOLD causée par broche
9=MESSAGE OPÉRATEUR - Machine en HOLD de Protections
10=OPERATOR MESSAGE - Tool magazine in potential collision with left side cover of the machine  
11=MESSAGE OPÉRATEUR - Broche en collision potentielle avec magasin
12=MESSAGE OPÉRATEUR - blocage exécutions FATM actif
13=MESSAGE OPÉRATEUR - Hold opening / closing Front Guard from Y, B, C axes position
14=MESSAGE OPÉRATEUR - attention: éventuel court-circuit sur les entrées à action non maintenue 
15=OPERATOR MESSAGE - Potential collision between tool and front guard
16=MESSAGE OPÉRATEUR - Sbloc. Ut. diretto possibile solo con ripari bassi
25=MESSAGE OPÉRATEUR - Graissage automatique désactivé
27=MESSAGE OPÉRATEUR - No security common outputs with safety switch on
30=MESSAGE OPÉRATEUR - Bridge password initialization done, restart
31=MESSAGE OPÉRATEUR - Counters file writing error
77=MESSAGE OPÉRATEUR - loading manual functions Error (MG Pilot)
78=MESSAGE OPÉRATEUR - loading manual functions Error (REM_CTRL)
80=OPERATOR MESSAGE - X axis motor in overload prealarm
81=OPERATOR MESSAGE - Y axis motor in overload prealarm
82=OPERATOR MESSAGE - Z axis motor in overload prealarm
83=OPERATOR MESSAGE - A axis motor in overload prealarm
84=OPERATOR MESSAGE - W axis motor in overload prealarm
88=OPERATOR MESSAGE - Voltage level low X axis encoder battery and absolute position lost
89=OPERATOR MESSAGE - Voltage level low Y axis encoder battery and absolute position lost
90=OPERATOR MESSAGE - Voltage level low Z axis encoder battery and absolute position lost
91=OPERATOR MESSAGE - Voltage level low A axis encoder battery and absolute position lost
92=OPERATOR MESSAGE - Voltage level low W axis encoder battery and absolute position lost
96=OPERATOR MESSAGE - Voltage level low X axis encoder battery
97=OPERATOR MESSAGE - Voltage level low Y axis encoder battery
98=OPERATOR MESSAGE - Voltage level low Z axis encoder battery
99=OPERATOR MESSAGE - Voltage level low A axis encoder battery
100=OPERATOR MESSAGE - Voltage level low W axis encoder battery
104=OPERATOR MESSAGE - X axis absolute encoder position not initialized
105=OPERATOR MESSAGE - Y axis absolute encoder position not initialized
106=OPERATOR MESSAGE - Z axis absolute encoder position not initialized
107=OPERATOR MESSAGE - A axis absolute encoder position not initialized
108=OPERATOR MESSAGE - W axis absolute encoder position not initialized
112=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn X axis encoder
113=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Y axis encoder
114=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn Z axis encoder
115=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn A axis encoder
116=OPERATOR MESSAGE - Overflow on the maximum revolutions of the absolute multiturn W axis encoder
