A          B ACTION. 
A OUVRIR   B FERMER 
A JOG -    B JOG + 
A DEPOT   B PRELEVE. 
A DESACT. B ACTIVAT. 
A ARRIERE  B AVANT 
A ROT.HOR. B ROT.ANT 
A FIN      B DEBUT 
A BLOCAGE  B DEBLOC. 
A GA       B DR 
