#pragma once

//:OPT_MOD_BEGIN
#include "omcnc72.h"
#include "omfile.h"
#include "omcan.h"
//:OPT_MOD_END

#include "..\messages.h"	// Messages definitions

extern USHORT DIGITALIN [20][18] ;
extern USHORT DIGITALOUT[20][18] ;
extern SHORT  ANALOGIN  [20][12] ;
extern SHORT  ANALOGOUT [20][6] ;
extern SHORT  ENCODERIN [20][1] ;

#pragma pack (push)
#pragma pack (4)

//:RTPLC_STRUCT_BEGIN
typedef struct _MM_COMPATIBLE {
	USHORT m[512];
} MM_COMPATIBLE,*PMM_COMPATIBLE;

typedef struct _REC_COMM {
	UCHAR rec_comm[256];
} REC_COMM,*PREC_COMM;

typedef struct _REC_COMM_DATA {
	UCHAR comm[256];
	ULONG code;
	ULONG len;
} REC_COMM_DATA,*PREC_COMM_DATA;

typedef struct _REC_COMM_QUEUE {
	REC_COMM_DATA data[10];
	UCHAR topIdx;
	UCHAR bottomIdx;
} REC_COMM_QUEUE,*PREC_COMM_QUEUE;

typedef struct _TIMER_DATA {
	LONG pilota;
	LONG hold;
	LONG memPilota;
	LONG rp;
	LONG rn;
	LONG dp;
	LONG dn;
	ULONG ritardo;
	LONG count;
} TIMER_DATA,*PTIMER_DATA;

typedef struct _FMAN_MAP {
	SHORT cntxCount;
	SHORT fmanCount;
	SHORT map[255];
} FMAN_MAP,*PFMAN_MAP;

typedef struct _TOOL_STRUCT {
	LONG tipo;
	FLOAT frequenzaRefrigerante;
	LONG numeroRefrigerante;
	LONG versoRotazione;
	FLOAT diametro[3];
	FLOAT lunghezza[3];
	FLOAT lunghezzaTotale;
	FLOAT diametroCodolo;
	FLOAT diametroPortaUtensile1;
	FLOAT lunghezzaPortaUtensile1;
	FLOAT diametroPortaUtensile2;
	FLOAT lunghezzaPortaUtensile2;
	LONG velocitaRotazioneMandrino;
	FLOAT velocitaAsportazione;
	FLOAT velocitaSfondamento;
	LONG presente;
} TOOL_STRUCT,*PTOOL_STRUCT;

typedef struct _TOOL_STORE_ENTRY_STRUCT {
	TOOL_STRUCT utensile[2];
} TOOL_STORE_ENTRY_STRUCT,*PTOOL_STORE_ENTRY_STRUCT;

typedef struct _TOOL_STORE_STRUCT {
	DOUBLE offsetX;
	DOUBLE offsetY;
	DOUBLE offsetZ;
	DOUBLE offsetAC;
	LONG numeroUtensili;
	TOOL_STORE_ENTRY_STRUCT magazzino[60];
} TOOL_STORE_STRUCT,*PTOOL_STORE_STRUCT;

typedef struct _GEST_AVA_TOOL_DRILL_CNC_STRUCT {
	LONG PosInStock;
	LONG Famiglia;
	DOUBLE Lunghezza;
	DOUBLE Raggio;
	DOUBLE DimTool;
	LONG NumLubrica;
	LONG NonUtilizzabile;
} GEST_AVA_TOOL_DRILL_CNC_STRUCT,*PGEST_AVA_TOOL_DRILL_CNC_STRUCT;

typedef struct _GEST_AVA_TOOL_CNC_DRILL_STRUCT {
	LONG ToolRotto;
	LONG ToolInLavoro;
} GEST_AVA_TOOL_CNC_DRILL_STRUCT,*PGEST_AVA_TOOL_CNC_DRILL_STRUCT;

typedef struct _T_LASER_INPUT_STRUCT {
	INT StepOver;
	INT AckMeasurementFinish;
} T_LASER_INPUT_STRUCT,*PT_LASER_INPUT_STRUCT;

typedef struct _T_LASER_OUTPUT_STRUCT {
	INT PositionReady;
	INT CmdResetStepOver;
	INT MeasurementFinish;
	INT MachineInAutomatic;
	FLOAT ActualPositionX;
	FLOAT ActualPositionY;
	FLOAT ActualPositionZ;
} T_LASER_OUTPUT_STRUCT,*PT_LASER_OUTPUT_STRUCT;

typedef struct _PLCEXTCOMMEX_LOCVARS {
	UCHAR dummy;
} PLCEXTCOMMEX_LOCVARS,*PPLCEXTCOMMEX_LOCVARS;

typedef struct _PLCGESTTASTO_LOCVARS {
	UCHAR dummy;
} PLCGESTTASTO_LOCVARS,*PPLCGESTTASTO_LOCVARS;

typedef struct _PLCTERMINATE_LOCVARS {
	UCHAR dummy;
} PLCTERMINATE_LOCVARS,*PPLCTERMINATE_LOCVARS;

typedef struct _PLCRESET_LOCVARS {
	UCHAR dummy;
} PLCRESET_LOCVARS,*PPLCRESET_LOCVARS;

typedef struct _PLCINIT_LOCVARS {
	UCHAR dummy;
} PLCINIT_LOCVARS,*PPLCINIT_LOCVARS;

typedef struct _PLCMAIN_LOCVARS {
	CNCPLC_AXIS_STATUS AXSTATUS[12];
	CNCPLC_AXIS_CTRL AXCTRL[12];
	CNPLC_CNCSTATUS CNCSTATUS;
	CNPLC_CNCCTRL CNCCTRL;
	CNPLC_HANDLE CNPLCHANDLE;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchAbort_AX_X;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchPos_AX_X;
	RTPLC_BIT latch_success_AX_X;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchAbort_AX_Y;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchPos_AX_Y;
	RTPLC_BIT latch_success_AX_Y;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchAbort_AX_Z;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchPos_AX_Z;
	RTPLC_BIT latch_success_AX_Z;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchAbort_AX_P;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchPos_AX_P;
	RTPLC_BIT latch_success_AX_P;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchAbort_AX_H;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT FB_LatchPos_AX_H;
	RTPLC_BIT latch_success_AX_H;
	LONG pilotStatus;
	USHORT DIGITALIN_00_00;
	USHORT DIGITALIN_00_01;
	USHORT DIGITALIN_00_02;
	USHORT DIGITALIN_00_03;
	USHORT DIGITALIN_00_04;
	USHORT DIGITALIN_00_05;
	USHORT DIGITALIN_00_06;
	USHORT DIGITALIN_00_07;
	USHORT DIGITALIN_00_08;
	USHORT DIGITALIN_00_09;
	USHORT DIGITALIN_00_10;
	USHORT DIGITALIN_00_11;
	USHORT DIGITALIN_00_12;
	USHORT DIGITALIN_00_13;
	USHORT DIGITALIN_00_14;
	USHORT DIGITALIN_00_15;
	USHORT DIGITALIN_00_16;
	USHORT DIGITALIN_00_17;
	USHORT DIGITALOUT_00_00;
	USHORT DIGITALOUT_00_01;
	USHORT DIGITALOUT_00_02;
	USHORT DIGITALOUT_00_03;
	USHORT DIGITALOUT_00_04;
	USHORT DIGITALOUT_00_05;
	USHORT DIGITALOUT_00_06;
	USHORT DIGITALOUT_00_07;
	USHORT DIGITALOUT_00_08;
	USHORT DIGITALOUT_00_09;
	USHORT DIGITALOUT_00_10;
	USHORT DIGITALOUT_00_11;
	USHORT DIGITALOUT_00_12;
	USHORT DIGITALOUT_00_13;
	USHORT DIGITALOUT_00_14;
	USHORT DIGITALOUT_00_15;
	USHORT DIGITALOUT_00_16;
	USHORT DIGITALOUT_00_17;
	SHORT ANALOGIN_00_00;
	SHORT ANALOGIN_00_01;
	SHORT ANALOGIN_00_02;
	SHORT ANALOGIN_00_03;
	SHORT ANALOGIN_00_04;
	SHORT ANALOGIN_00_05;
	SHORT ANALOGIN_00_06;
	SHORT ANALOGIN_00_07;
	SHORT ANALOGIN_00_08;
	SHORT ANALOGIN_00_09;
	SHORT ANALOGIN_00_10;
	SHORT ANALOGIN_00_11;
	SHORT ANALOGOUT_00_00;
	SHORT ANALOGOUT_00_01;
	SHORT ANALOGOUT_00_02;
	SHORT ANALOGOUT_00_03;
	SHORT ANALOGOUT_00_04;
	SHORT ANALOGOUT_00_05;
	SHORT ENCODERIN_00_00;
	USHORT DIGITALIN_01_00;
	USHORT DIGITALIN_01_01;
	USHORT DIGITALIN_01_02;
	USHORT DIGITALOUT_01_00;
	USHORT DIGITALOUT_01_01;
	USHORT DIGITALOUT_01_02;
	SHORT ANALOGIN_01_00;
	SHORT ANALOGIN_01_01;
	SHORT ANALOGOUT_01_00;
	USHORT DIGITALIN_02_00;
	USHORT DIGITALIN_02_01;
	USHORT DIGITALIN_02_02;
	USHORT DIGITALOUT_02_00;
	USHORT DIGITALOUT_02_01;
	USHORT DIGITALOUT_02_02;
	SHORT ANALOGIN_02_00;
	SHORT ANALOGIN_02_01;
	SHORT ANALOGOUT_02_00;
	USHORT DIGITALIN_03_00;
	USHORT DIGITALIN_03_01;
	USHORT DIGITALIN_03_02;
	USHORT DIGITALOUT_03_00;
	USHORT DIGITALOUT_03_01;
	USHORT DIGITALOUT_03_02;
	SHORT ANALOGIN_03_00;
	SHORT ANALOGIN_03_01;
	SHORT ANALOGOUT_03_00;
	USHORT DIGITALIN_04_00;
	USHORT DIGITALIN_04_01;
	USHORT DIGITALIN_04_02;
	USHORT DIGITALOUT_04_00;
	USHORT DIGITALOUT_04_01;
	SHORT ANALOGIN_04_00;
	SHORT ANALOGIN_04_01;
	USHORT DIGITALIN_05_00;
	USHORT DIGITALIN_05_01;
	USHORT DIGITALIN_05_02;
	USHORT DIGITALIN_05_03;
	USHORT DIGITALIN_05_04;
	USHORT DIGITALIN_05_05;
	USHORT DIGITALIN_05_06;
	USHORT DIGITALIN_05_07;
	USHORT DIGITALIN_05_08;
	USHORT DIGITALIN_05_09;
	USHORT DIGITALIN_05_10;
	USHORT DIGITALIN_05_11;
	USHORT DIGITALOUT_05_00;
	ULONGLONG highresClk;
	CNPLC_CNCCTRL CNCCTRL_l_CH1;
	CNPLC_CNCSTATUS CNCSTATUS_l_CH1;
	CNPLC_HANDLE CNPLCHANDLE_l_CH1;
	CNCPLC_AXIS_CTRL AXCTRL_l_CH1[12];
	CNCPLC_AXIS_STATUS AXSTATUS_l_CH1[12];
	CNPLC_CNCCTRL CNCCTRL_l_CH2;
	CNPLC_CNCSTATUS CNCSTATUS_l_CH2;
	CNPLC_HANDLE CNPLCHANDLE_l_CH2;
	CNCPLC_AXIS_CTRL AXCTRL_l_CH2[12];
	CNCPLC_AXIS_STATUS AXSTATUS_l_CH2[12];
	CNPLC_CNCCTRL CNCCTRL_l_CH3;
	CNPLC_CNCSTATUS CNCSTATUS_l_CH3;
	CNPLC_HANDLE CNPLCHANDLE_l_CH3;
	CNCPLC_AXIS_CTRL AXCTRL_l_CH3[12];
	CNCPLC_AXIS_STATUS AXSTATUS_l_CH3[12];
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearIn_ch0;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearIn_ch1;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearIn_ch2;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearIn_ch3;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearOut_ch0;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearOut_ch1;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearOut_ch2;
	RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fbGearOut_ch3;
} PLCMAIN_LOCVARS,*PPLCMAIN_LOCVARS;

typedef struct _PLCMAIN_GLOBVARS {
	T_LASER_INPUT_STRUCT t_laser_input_shared;
	T_LASER_OUTPUT_STRUCT t_laser_output_shared;
} PLCMAIN_GLOBVARS,*PPLCMAIN_GLOBVARS;

//:RTPLC_STRUCT_END

//typedef struct _GIANO_SHAREDMEM {
//	UCHAR sharedmem[SCHECMD_SHAREDMEM_TOTAL_LENGTH];
//} GIANO_SHAREDMEM, *PGIANO_SHAREDMEM;

//:RTPLC_SYNONYMDEF_BEGIN
__DEFINE PLCMAIN_GLOBVARS variabili_globali ;
__DEFINE UCHAR plcExtCommex_dummy ;
__DEFINE UCHAR plcGestTasto_dummy ;
__DEFINE REC_COMM rec_comm[10] ;
__DEFINE ULONG rec_code[10] ;
__DEFINE USHORT rec_datalen[10] ;
__DEFINE UCHAR rec_queuetop ;
__DEFINE UCHAR rec_queuebottom ;
__DEFINE PMM_COMPATIBLE p_ms ;
__DEFINE CNCPLC_AXIS_STATUS AXSTATUS[12] ;
__DEFINE CNCPLC_AXIS_CTRL AXCTRL[12] ;
__DEFINE CNPLC_CNCSTATUS CNCSTATUS ;
__DEFINE CNPLC_CNCCTRL CNCCTRL ;
__DEFINE CNPLC_HANDLE CNPLCHANDLE ;
__DEFINE CNCPLC_AXIS_STATUS plcMain_AXSTATUS[12] ;
__DEFINE CNCPLC_AXIS_CTRL plcMain_AXCTRL[12] ;
__DEFINE CNPLC_CNCSTATUS plcMain_CNCSTATUS ;
__DEFINE CNPLC_CNCCTRL plcMain_CNCCTRL ;
__DEFINE CNPLC_HANDLE plcMain_CNPLCHANDLE ;
__DEFINE CONF_CN CONFCN ;
__DEFINE CNPLC_PROGRAM_STATUS PROGRAMSTATUS ;
__DEFINE CNPLC_TOOL_STATUS TOOLSTATUS ;
__DEFINE UCHAR plcTerminate_dummy ;
__DEFINE UCHAR plcReset_dummy ;
__DEFINE LONG plcStatus ;
__DEFINE REC_COMM_QUEUE recComm ;
__DEFINE UCHAR plcInit_dummy ;
__DEFINE RTPLC_BIT waitDebugger ;
__DEFINE TIMER_DATA TSuppl[1024] ;
__DEFINE TIMER_DATA TSimu[1024] ;
__DEFINE FMAN_MAP fmanMap ;
__DEFINE RTPLC_BIT LatchAbort_Error_AX_X ;
__DEFINE RTPLC_BIT FB_LatchAbort_Execute_AX_X ;
__DEFINE SHORT LatchAbort_ErrorID_AX_X ;
__DEFINE RTPLC_BIT LatchAbort_Done_AX_X ;
__DEFINE RTPLC_BIT LatchAbort_Busy_AX_X ;
__DEFINE RTPLC_BIT FB_LatchPos_Execute_AX_X ;
__DEFINE RTPLC_BIT LatchPos_Error_AX_X ;
__DEFINE SHORT LatchPos_ErrorID_AX_X ;
__DEFINE RTPLC_BIT LatchPos_Done_AX_X ;
__DEFINE RTPLC_BIT LatchPos_Busy_AX_X ;
__DEFINE RTPLC_BIT latchError_AX_X ;
__DEFINE RTPLC_BIT latchArrived_AX_X ;
__DEFINE RTPLC_BIT latchArrived2_AX_X ;
__DEFINE DOUBLE latchPosition_AX_X ;
__DEFINE DOUBLE latchPosition2_AX_X ;
__DEFINE RTPLC_BIT latch_abort_condition_AX_X ;
__DEFINE RTPLC_BIT latch_err_AX_X ;
__DEFINE RTPLC_BIT latch_start_condition_AX_X ;
__DEFINE DOUBLE pos_value_touch1_AX_X ;
__DEFINE DOUBLE pos_value_touch2_AX_X ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchAbort_AX_X ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchPos_AX_X ;
__DEFINE RTPLC_BIT plcMain_latch_success_AX_X ;
__DEFINE RTPLC_BIT LatchAbort_Error_AX_Y ;
__DEFINE RTPLC_BIT FB_LatchAbort_Execute_AX_Y ;
__DEFINE SHORT LatchAbort_ErrorID_AX_Y ;
__DEFINE RTPLC_BIT LatchAbort_Done_AX_Y ;
__DEFINE RTPLC_BIT LatchAbort_Busy_AX_Y ;
__DEFINE RTPLC_BIT FB_LatchPos_Execute_AX_Y ;
__DEFINE RTPLC_BIT LatchPos_Error_AX_Y ;
__DEFINE SHORT LatchPos_ErrorID_AX_Y ;
__DEFINE RTPLC_BIT LatchPos_Done_AX_Y ;
__DEFINE RTPLC_BIT LatchPos_Busy_AX_Y ;
__DEFINE RTPLC_BIT latchError_AX_Y ;
__DEFINE RTPLC_BIT latchArrived_AX_Y ;
__DEFINE RTPLC_BIT latchArrived2_AX_Y ;
__DEFINE DOUBLE latchPosition_AX_Y ;
__DEFINE DOUBLE latchPosition2_AX_Y ;
__DEFINE RTPLC_BIT latch_abort_condition_AX_Y ;
__DEFINE RTPLC_BIT latch_err_AX_Y ;
__DEFINE RTPLC_BIT latch_start_condition_AX_Y ;
__DEFINE DOUBLE pos_value_touch1_AX_Y ;
__DEFINE DOUBLE pos_value_touch2_AX_Y ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchAbort_AX_Y ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchPos_AX_Y ;
__DEFINE RTPLC_BIT plcMain_latch_success_AX_Y ;
__DEFINE RTPLC_BIT LatchAbort_Error_AX_Z ;
__DEFINE RTPLC_BIT FB_LatchAbort_Execute_AX_Z ;
__DEFINE SHORT LatchAbort_ErrorID_AX_Z ;
__DEFINE RTPLC_BIT LatchAbort_Done_AX_Z ;
__DEFINE RTPLC_BIT LatchAbort_Busy_AX_Z ;
__DEFINE RTPLC_BIT FB_LatchPos_Execute_AX_Z ;
__DEFINE RTPLC_BIT LatchPos_Error_AX_Z ;
__DEFINE SHORT LatchPos_ErrorID_AX_Z ;
__DEFINE RTPLC_BIT LatchPos_Done_AX_Z ;
__DEFINE RTPLC_BIT LatchPos_Busy_AX_Z ;
__DEFINE RTPLC_BIT latchError_AX_Z ;
__DEFINE RTPLC_BIT latchArrived_AX_Z ;
__DEFINE RTPLC_BIT latchArrived2_AX_Z ;
__DEFINE DOUBLE latchPosition_AX_Z ;
__DEFINE DOUBLE latchPosition2_AX_Z ;
__DEFINE RTPLC_BIT latch_abort_condition_AX_Z ;
__DEFINE RTPLC_BIT latch_err_AX_Z ;
__DEFINE RTPLC_BIT latch_start_condition_AX_Z ;
__DEFINE DOUBLE pos_value_touch1_AX_Z ;
__DEFINE DOUBLE pos_value_touch2_AX_Z ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchAbort_AX_Z ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchPos_AX_Z ;
__DEFINE RTPLC_BIT plcMain_latch_success_AX_Z ;
__DEFINE RTPLC_BIT LatchAbort_Error_AX_P ;
__DEFINE RTPLC_BIT FB_LatchAbort_Execute_AX_P ;
__DEFINE SHORT LatchAbort_ErrorID_AX_P ;
__DEFINE RTPLC_BIT LatchAbort_Done_AX_P ;
__DEFINE RTPLC_BIT LatchAbort_Busy_AX_P ;
__DEFINE RTPLC_BIT FB_LatchPos_Execute_AX_P ;
__DEFINE RTPLC_BIT LatchPos_Error_AX_P ;
__DEFINE SHORT LatchPos_ErrorID_AX_P ;
__DEFINE RTPLC_BIT LatchPos_Done_AX_P ;
__DEFINE RTPLC_BIT LatchPos_Busy_AX_P ;
__DEFINE RTPLC_BIT latchError_AX_P ;
__DEFINE RTPLC_BIT latchArrived_AX_P ;
__DEFINE RTPLC_BIT latchArrived2_AX_P ;
__DEFINE DOUBLE latchPosition_AX_P ;
__DEFINE DOUBLE latchPosition2_AX_P ;
__DEFINE RTPLC_BIT latch_abort_condition_AX_P ;
__DEFINE RTPLC_BIT latch_err_AX_P ;
__DEFINE RTPLC_BIT latch_start_condition_AX_P ;
__DEFINE DOUBLE pos_value_touch1_AX_P ;
__DEFINE DOUBLE pos_value_touch2_AX_P ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchAbort_AX_P ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchPos_AX_P ;
__DEFINE RTPLC_BIT plcMain_latch_success_AX_P ;
__DEFINE RTPLC_BIT LatchAbort_Error_AX_H ;
__DEFINE RTPLC_BIT FB_LatchAbort_Execute_AX_H ;
__DEFINE SHORT LatchAbort_ErrorID_AX_H ;
__DEFINE RTPLC_BIT LatchAbort_Done_AX_H ;
__DEFINE RTPLC_BIT LatchAbort_Busy_AX_H ;
__DEFINE RTPLC_BIT FB_LatchPos_Execute_AX_H ;
__DEFINE RTPLC_BIT LatchPos_Error_AX_H ;
__DEFINE SHORT LatchPos_ErrorID_AX_H ;
__DEFINE RTPLC_BIT LatchPos_Done_AX_H ;
__DEFINE RTPLC_BIT LatchPos_Busy_AX_H ;
__DEFINE RTPLC_BIT latchError_AX_H ;
__DEFINE RTPLC_BIT latchArrived_AX_H ;
__DEFINE RTPLC_BIT latchArrived2_AX_H ;
__DEFINE DOUBLE latchPosition_AX_H ;
__DEFINE DOUBLE latchPosition2_AX_H ;
__DEFINE RTPLC_BIT latch_abort_condition_AX_H ;
__DEFINE RTPLC_BIT latch_err_AX_H ;
__DEFINE RTPLC_BIT latch_start_condition_AX_H ;
__DEFINE DOUBLE pos_value_touch1_AX_H ;
__DEFINE DOUBLE pos_value_touch2_AX_H ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchAbort_AX_H ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_FB_LatchPos_AX_H ;
__DEFINE RTPLC_BIT plcMain_latch_success_AX_H ;
__DEFINE LONG plcMain_pilotStatus ;
__DEFINE USHORT plcMain_DIGITALIN_00_00 ;
__DEFINE USHORT plcMain_DIGITALIN_00_01 ;
__DEFINE USHORT plcMain_DIGITALIN_00_02 ;
__DEFINE USHORT plcMain_DIGITALIN_00_03 ;
__DEFINE USHORT plcMain_DIGITALIN_00_04 ;
__DEFINE USHORT plcMain_DIGITALIN_00_05 ;
__DEFINE USHORT plcMain_DIGITALIN_00_06 ;
__DEFINE USHORT plcMain_DIGITALIN_00_07 ;
__DEFINE USHORT plcMain_DIGITALIN_00_08 ;
__DEFINE USHORT plcMain_DIGITALIN_00_09 ;
__DEFINE USHORT plcMain_DIGITALIN_00_10 ;
__DEFINE USHORT plcMain_DIGITALIN_00_11 ;
__DEFINE USHORT plcMain_DIGITALIN_00_12 ;
__DEFINE USHORT plcMain_DIGITALIN_00_13 ;
__DEFINE USHORT plcMain_DIGITALIN_00_14 ;
__DEFINE USHORT plcMain_DIGITALIN_00_15 ;
__DEFINE USHORT plcMain_DIGITALIN_00_16 ;
__DEFINE USHORT plcMain_DIGITALIN_00_17 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_00 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_01 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_02 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_03 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_04 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_05 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_06 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_07 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_08 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_09 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_10 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_11 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_12 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_13 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_14 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_15 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_16 ;
__DEFINE USHORT plcMain_DIGITALOUT_00_17 ;
__DEFINE SHORT plcMain_ANALOGIN_00_00 ;
__DEFINE SHORT plcMain_ANALOGIN_00_01 ;
__DEFINE SHORT plcMain_ANALOGIN_00_02 ;
__DEFINE SHORT plcMain_ANALOGIN_00_03 ;
__DEFINE SHORT plcMain_ANALOGIN_00_04 ;
__DEFINE SHORT plcMain_ANALOGIN_00_05 ;
__DEFINE SHORT plcMain_ANALOGIN_00_06 ;
__DEFINE SHORT plcMain_ANALOGIN_00_07 ;
__DEFINE SHORT plcMain_ANALOGIN_00_08 ;
__DEFINE SHORT plcMain_ANALOGIN_00_09 ;
__DEFINE SHORT plcMain_ANALOGIN_00_10 ;
__DEFINE SHORT plcMain_ANALOGIN_00_11 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_00 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_01 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_02 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_03 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_04 ;
__DEFINE SHORT plcMain_ANALOGOUT_00_05 ;
__DEFINE SHORT plcMain_ENCODERIN_00_00 ;
__DEFINE USHORT plcMain_DIGITALIN_01_00 ;
__DEFINE USHORT plcMain_DIGITALIN_01_01 ;
__DEFINE USHORT plcMain_DIGITALIN_01_02 ;
__DEFINE USHORT plcMain_DIGITALOUT_01_00 ;
__DEFINE USHORT plcMain_DIGITALOUT_01_01 ;
__DEFINE USHORT plcMain_DIGITALOUT_01_02 ;
__DEFINE SHORT plcMain_ANALOGIN_01_00 ;
__DEFINE SHORT plcMain_ANALOGIN_01_01 ;
__DEFINE SHORT plcMain_ANALOGOUT_01_00 ;
__DEFINE USHORT plcMain_DIGITALIN_02_00 ;
__DEFINE USHORT plcMain_DIGITALIN_02_01 ;
__DEFINE USHORT plcMain_DIGITALIN_02_02 ;
__DEFINE USHORT plcMain_DIGITALOUT_02_00 ;
__DEFINE USHORT plcMain_DIGITALOUT_02_01 ;
__DEFINE USHORT plcMain_DIGITALOUT_02_02 ;
__DEFINE SHORT plcMain_ANALOGIN_02_00 ;
__DEFINE SHORT plcMain_ANALOGIN_02_01 ;
__DEFINE SHORT plcMain_ANALOGOUT_02_00 ;
__DEFINE USHORT plcMain_DIGITALIN_03_00 ;
__DEFINE USHORT plcMain_DIGITALIN_03_01 ;
__DEFINE USHORT plcMain_DIGITALIN_03_02 ;
__DEFINE USHORT plcMain_DIGITALOUT_03_00 ;
__DEFINE USHORT plcMain_DIGITALOUT_03_01 ;
__DEFINE USHORT plcMain_DIGITALOUT_03_02 ;
__DEFINE SHORT plcMain_ANALOGIN_03_00 ;
__DEFINE SHORT plcMain_ANALOGIN_03_01 ;
__DEFINE SHORT plcMain_ANALOGOUT_03_00 ;
__DEFINE USHORT plcMain_DIGITALIN_04_00 ;
__DEFINE USHORT plcMain_DIGITALIN_04_01 ;
__DEFINE USHORT plcMain_DIGITALIN_04_02 ;
__DEFINE USHORT plcMain_DIGITALOUT_04_00 ;
__DEFINE USHORT plcMain_DIGITALOUT_04_01 ;
__DEFINE SHORT plcMain_ANALOGIN_04_00 ;
__DEFINE SHORT plcMain_ANALOGIN_04_01 ;
__DEFINE USHORT plcMain_DIGITALIN_05_00 ;
__DEFINE USHORT plcMain_DIGITALIN_05_01 ;
__DEFINE USHORT plcMain_DIGITALIN_05_02 ;
__DEFINE USHORT plcMain_DIGITALIN_05_03 ;
__DEFINE USHORT plcMain_DIGITALIN_05_04 ;
__DEFINE USHORT plcMain_DIGITALIN_05_05 ;
__DEFINE USHORT plcMain_DIGITALIN_05_06 ;
__DEFINE USHORT plcMain_DIGITALIN_05_07 ;
__DEFINE USHORT plcMain_DIGITALIN_05_08 ;
__DEFINE USHORT plcMain_DIGITALIN_05_09 ;
__DEFINE USHORT plcMain_DIGITALIN_05_10 ;
__DEFINE USHORT plcMain_DIGITALIN_05_11 ;
__DEFINE USHORT plcMain_DIGITALOUT_05_00 ;
__DEFINE LONG ToolTabS1 ;
__DEFINE LONG ToolTabS2 ;
__DEFINE TOOL_STORE_STRUCT SynoToolStruct ;
__DEFINE GEST_AVA_TOOL_DRILL_CNC_STRUCT GestAvaToolDrillToCnc[60] ;
__DEFINE GEST_AVA_TOOL_CNC_DRILL_STRUCT GestAvaToolCncToDrill[60] ;
__DEFINE LONG NumToolNonUtilizzabile ;
__DEFINE LONG AliveDrillToCnc ;
__DEFINE LONG AliveCncToDrill ;
__DEFINE RTPLC_DAYTIME dayTime ;
__DEFINE RTPLC_BUSINNESSTIME dateTime ;
__DEFINE ULONGLONG highresClk ;
__DEFINE ULONGLONG plcMain_highresClk ;
__DEFINE LONG CNT_COMMAND_2 ;
__DEFINE INT opcUaNumSpindles[16] ;
//Ch1
__DEFINE PMM_COMPATIBLE p_ms_CH1 ;
__DEFINE CNPLC_CNCCTRL CNCCTRL_CH1 ;
__DEFINE CNPLC_CNCSTATUS CNCSTATUS_CH1 ;
__DEFINE CNPLC_HANDLE CNPLCHANDLE_CH1 ;
__DEFINE CNCPLC_AXIS_CTRL AXCTRL_CH1[12] ;
__DEFINE CNPLC_CNCCTRL plcMain_CNCCTRL_l_CH1 ;
__DEFINE CNPLC_CNCSTATUS plcMain_CNCSTATUS_l_CH1 ;
__DEFINE CNPLC_HANDLE plcMain_CNPLCHANDLE_l_CH1 ;
__DEFINE CNCPLC_AXIS_CTRL plcMain_AXCTRL_l_CH1[12] ;
__DEFINE CNCPLC_AXIS_STATUS plcMain_AXSTATUS_l_CH1[12] ;
__DEFINE CNCPLC_AXIS_STATUS AXSTATUS_CH1[12] ;
__DEFINE CONF_CN CONFCN_CH1 ;
//Ch2
__DEFINE PMM_COMPATIBLE p_ms_CH2 ;
__DEFINE CNPLC_CNCCTRL CNCCTRL_CH2 ;
__DEFINE CNPLC_CNCSTATUS CNCSTATUS_CH2 ;
__DEFINE CNPLC_HANDLE CNPLCHANDLE_CH2 ;
__DEFINE CNCPLC_AXIS_CTRL AXCTRL_CH2[12] ;
__DEFINE CNCPLC_AXIS_STATUS AXSTATUS_CH2[12] ;
__DEFINE CNPLC_CNCCTRL plcMain_CNCCTRL_l_CH2 ;
__DEFINE CNPLC_CNCSTATUS plcMain_CNCSTATUS_l_CH2 ;
__DEFINE CNCPLC_AXIS_CTRL plcMain_AXCTRL_l_CH2[12] ;
__DEFINE CNCPLC_AXIS_STATUS plcMain_AXSTATUS_l_CH2[12] ;
__DEFINE CNPLC_HANDLE plcMain_CNPLCHANDLE_l_CH2 ;
__DEFINE CONF_CN CONFCN_CH2 ;
//Ch3
__DEFINE PMM_COMPATIBLE p_ms_CH3 ;
__DEFINE CNPLC_CNCCTRL CNCCTRL_CH3 ;
__DEFINE CNPLC_CNCSTATUS CNCSTATUS_CH3 ;
__DEFINE CNPLC_HANDLE CNPLCHANDLE_CH3 ;
__DEFINE CNCPLC_AXIS_CTRL AXCTRL_CH3[12] ;
__DEFINE CNCPLC_AXIS_STATUS AXSTATUS_CH3[12] ;
__DEFINE CNPLC_CNCCTRL plcMain_CNCCTRL_l_CH3 ;
__DEFINE CNPLC_CNCSTATUS plcMain_CNCSTATUS_l_CH3 ;
__DEFINE CNPLC_HANDLE plcMain_CNPLCHANDLE_l_CH3 ;
__DEFINE CNCPLC_AXIS_CTRL plcMain_AXCTRL_l_CH3[12] ;
__DEFINE CNCPLC_AXIS_STATUS plcMain_AXSTATUS_l_CH3[12] ;
__DEFINE CONF_CN CONFCN_CH3 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearIn_ch0 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearIn_ch1 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearIn_ch2 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearIn_ch3 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearOut_ch0 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearOut_ch1 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearOut_ch2 ;
__DEFINE RTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT plcMain_fbGearOut_ch3 ;

//:RTPLC_SYNONYMDEF_END
//__DEFINE GIANO_SHAREDMEM GianoSharedAreaMaster;
//__DEFINE GIANO_SHAREDMEM GianoSharedAreaSlave0;
//__DEFINE GIANO_SHAREDMEM GianoSharedAreaSlave1;
//__DEFINE GIANO_SHAREDMEM GianoSharedAreaSlave2;
//__DEFINE GIANO_SHAREDMEM GianoSharedAreaSlave3;
//__DEFINE USHORT GianoReservedMaster;
//__DEFINE USHORT GianoReservedSlave;
__DEFINE ULONG rec_tasto ;

//:RTPLC_EVENTDEF_BEGIN
void RTPLC_ROUTINE plcExtCommex(PRTPLC_EXTCOMM_STRUCT data);
void RTPLC_ROUTINE plcGestTasto(PRTPLC_EXTCOMM_STRUCT data);
void RTPLC_ROUTINE plcTerminate(LPVOID data);
void RTPLC_ROUTINE plcReset(LPVOID data);
void RTPLC_ROUTINE plcInit(LPVOID data);
void RTPLC_ROUTINE plcMain(LPVOID data);

//:RTPLC_EVENTDEF_END

//:RTPLC_PROXYFUNC_BEGIN
void __inline Omcnc_LatchAbort (PRTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fb, RTPLC_BIT Execute, SHORT channelIndex, SHORT axisIndex, RTPLC_BIT * Done, RTPLC_BIT * Busy, RTPLC_BIT * Error, SHORT * ErrorID) {
	RTPLC_VARIANT param [7];
	param [0].vt = RTPLC_FORMAT_BIT; param [0].value.boolean = Execute;
	param [1].vt = RTPLC_FORMAT_INT16; param [1].value.s = channelIndex;
	param [2].vt = RTPLC_FORMAT_INT16; param [2].value.s = axisIndex;
	param [3].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [3].value.pboolean = Done;
	param [4].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [4].value.pboolean = Busy;
	param [5].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [5].value.pboolean = Error;
	param [6].vt = RTPLC_FORMAT_INT16 | RTPLC_FORMAT_BYREF; param [6].value.ps = ErrorID;
	invokeFuncblk (fb, param, 7, NULL);
}
void __inline Omcnc_LatchPos (PRTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fb, RTPLC_BIT Execute, SHORT channelIndex, SHORT axisIndex, SHORT indexLatch, RTPLC_BIT FrontNegative, double maxdistance, RTPLC_BIT * Done, RTPLC_BIT * Busy, RTPLC_BIT * Error, SHORT * ErrorID, RTPLC_BIT * latchError, RTPLC_BIT * latchArrived, RTPLC_BIT * latchArrived2, double * latchPosition, double * latchPosition2) {
	RTPLC_VARIANT param [15];
	param [0].vt = RTPLC_FORMAT_BIT; param [0].value.boolean = Execute;
	param [1].vt = RTPLC_FORMAT_INT16; param [1].value.s = channelIndex;
	param [2].vt = RTPLC_FORMAT_INT16; param [2].value.s = axisIndex;
	param [3].vt = RTPLC_FORMAT_INT16; param [3].value.s = indexLatch;
	param [4].vt = RTPLC_FORMAT_BIT; param [4].value.boolean = FrontNegative;
	param [5].vt = RTPLC_FORMAT_DOUBLE; param [5].value.d = maxdistance;
	param [6].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [6].value.pboolean = Done;
	param [7].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [7].value.pboolean = Busy;
	param [8].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [8].value.pboolean = Error;
	param [9].vt = RTPLC_FORMAT_INT16 | RTPLC_FORMAT_BYREF; param [9].value.ps = ErrorID;
	param [10].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [10].value.pboolean = latchError;
	param [11].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [11].value.pboolean = latchArrived;
	param [12].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [12].value.pboolean = latchArrived2;
	param [13].vt = RTPLC_FORMAT_DOUBLE | RTPLC_FORMAT_BYREF; param [13].value.pd = latchPosition;
	param [14].vt = RTPLC_FORMAT_DOUBLE | RTPLC_FORMAT_BYREF; param [14].value.pd = latchPosition2;
	invokeFuncblk (fb, param, 15, NULL);
}
void __inline Omcnc_GearIn (PRTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fb, RTPLC_BIT Execute, CNPLC_CNCSTATUS * CncStatus, CNCPLC_AXIS_STATUS * Master_Status, USHORT Master_Index, CNCPLC_AXIS_STATUS * Slave_Status /* arraySize=15 */, USHORT * Slave_ChAxIndex /* arraySize=15 */, double GainGantry, double FligthGantry, double * GantryRatio /* arraySize=15 */, USHORT LineGantry, RTPLC_BIT * InGear, RTPLC_BIT * Busy, RTPLC_BIT * Error, SHORT * ErrorID) {
	RTPLC_VARIANT param [14];
	param [0].vt = RTPLC_FORMAT_BIT; param [0].value.boolean = Execute;
	param [1].vt = RTPLC_FORMAT_STRUCT; param [1].value.varstruct.arraySize = 1; param [1].value.varstruct.size = sizeof (*CncStatus); param [1].value.varstruct.structPt = CncStatus;
	param [2].vt = RTPLC_FORMAT_STRUCT; param [2].value.varstruct.arraySize = 1; param [2].value.varstruct.size = sizeof (*Master_Status); param [2].value.varstruct.structPt = Master_Status;
	param [3].vt = RTPLC_FORMAT_UINT16; param [3].value.us = Master_Index;
	param [4].vt = RTPLC_FORMAT_STRUCT; param [4].value.varstruct.arraySize = 15; param [4].value.varstruct.size = sizeof (*Slave_Status); param [4].value.varstruct.structPt = Slave_Status;
	param [5].vt = (RTPLC_FORMAT_ARRAY | RTPLC_FORMAT_UINT16); param[5].value.arr.size = 15; param[5].value.arr.data = Slave_ChAxIndex;
	param [6].vt = RTPLC_FORMAT_DOUBLE; param [6].value.d = GainGantry;
	param [7].vt = RTPLC_FORMAT_DOUBLE; param [7].value.d = FligthGantry;
	param [8].vt = (RTPLC_FORMAT_ARRAY | RTPLC_FORMAT_DOUBLE); param[8].value.arr.size = 15; param[8].value.arr.data = GantryRatio;
	param [9].vt = RTPLC_FORMAT_UINT16; param [9].value.us = LineGantry;
	param [10].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [10].value.pboolean = InGear;
	param [11].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [11].value.pboolean = Busy;
	param [12].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [12].value.pboolean = Error;
	param [13].vt = RTPLC_FORMAT_INT16 | RTPLC_FORMAT_BYREF; param [13].value.ps = ErrorID;
	invokeFuncblk (fb, param, 14, NULL);
}

void __inline Omcnc_GearOut (PRTPLC_SYNONYM_FUNCTIONBLOCK_STRUCT fb, RTPLC_BIT Execute, CNPLC_CNCSTATUS * CncStatus, USHORT Master_Index, USHORT * Slave_ChAxIndex /* arraySize=15 */, RTPLC_BIT * Done, RTPLC_BIT * Busy, RTPLC_BIT * Error, SHORT * ErrorID) {
	RTPLC_VARIANT param [8];
	param [0].vt = RTPLC_FORMAT_BIT; param [0].value.boolean = Execute;
	param [1].vt = RTPLC_FORMAT_STRUCT; param [1].value.varstruct.arraySize = 1; param [1].value.varstruct.size = sizeof (*CncStatus); param [1].value.varstruct.structPt = CncStatus;
	param [2].vt = RTPLC_FORMAT_UINT16; param [2].value.us = Master_Index;
	param [3].vt = (RTPLC_FORMAT_ARRAY | RTPLC_FORMAT_UINT16); param[3].value.arr.size = 15; param [3].value.arr.data = Slave_ChAxIndex;
	param [4].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [4].value.pboolean = Done;
	param [5].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [5].value.pboolean = Busy;
	param [6].vt = RTPLC_FORMAT_BIT | RTPLC_FORMAT_BYREF; param [6].value.pboolean = Error;
	param [7].vt = RTPLC_FORMAT_INT16 | RTPLC_FORMAT_BYREF; param [7].value.ps = ErrorID;
	invokeFuncblk (fb, param, 8, NULL);
}

//:RTPLC_PROXYFUNC_END

__DEFINE DATI *p_m __INIT(NULL);
__DEFINE double *Aris __INIT(NULL);
__DEFINE double *Acus __INIT(NULL);
__DEFINE PCNCPLC_DATA p_dplc_v3 __INIT(NULL);

// oggetti globale di Giano
//__DEFINE SCHECMD_HEADER g_header;
//__DEFINE PPLC_IO_DATA2 g_pointerDataMem[SCHECMD_MAX_NODES];
//__DEFINE short g_OffSetArea[SCHECMD_MAX_NODES];
//__DEFINE UCHAR g_indexSelf __INIT(PLC_ETHERNET_O_ID_MASTER);
//__DEFINE HANDLE	g_Handle[2];
//__DEFINE ULONG g_ackMasterSlave;
//__DEFINE UCHAR indexSelf __INIT(PLC_ETHERNET_O_ID_MASTER); //identico a g_indexSelf
//__DEFINE PPLC_IO_DATA2 *pointerDataMem __INIT(g_pointerDataMem);
//__DEFINE PSCHECMD_HEADER pHeader __INIT(&g_header);

//strutture della navetta da inizializzare in main
__DEFINE PCKEY		 *ppckey __INIT(NULL);
__DEFINE N_XOUT		 *pn_xout __INIT(NULL);
__DEFINE N_XIN		 *pn_xin __INIT(NULL);
__DEFINE N_AREC_V3	 *pn_arec_v2 __INIT(NULL);
__DEFINE N_ARED_V3	 *pn_ared_v2 __INIT(NULL);
__DEFINE N_SAREC	 *pn_sarec __INIT(NULL);
__DEFINE N_KEY		 *pn_key __INIT(NULL);
__DEFINE IO_V3		 *pio_v2 __INIT(NULL);
__DEFINE DIAG		 *pdiag __INIT(NULL);
__DEFINE N_VISPLC_V2 *pn_visplc_v2 __INIT(NULL);
__DEFINE SIN		 *psin __INIT(NULL);
__DEFINE CNF_V2		 *pcnf_v2 __INIT(NULL);
__DEFINE ARETPLC_V4	 *paretplc_v2 __INIT(NULL);
__DEFINE N_DMAND_V3	 *pn_dmand __INIT(NULL);

//Ch1
__DEFINE DATI *p_m_CH1 __INIT(NULL);
__DEFINE double *Aris_CH1 __INIT(NULL);
__DEFINE double *Acus_CH1 __INIT(NULL);
__DEFINE PCNCPLC_DATA p_dplc_v3_CH1 __INIT(NULL);

//strutture della navetta da inizializzare in main
__DEFINE PCKEY		 *ppckey_CH1 __INIT(NULL);
__DEFINE N_XOUT		 *pn_xout_CH1 __INIT(NULL);
__DEFINE N_XIN		 *pn_xin_CH1 __INIT(NULL);
__DEFINE N_AREC_V3	 *pn_arec_v2_CH1 __INIT(NULL);
__DEFINE N_ARED_V3	 *pn_ared_v2_CH1 __INIT(NULL);
__DEFINE N_SAREC	 *pn_sarec_CH1 __INIT(NULL);
__DEFINE N_KEY		 *pn_key_CH1 __INIT(NULL);
__DEFINE IO_V3		 *pio_v2_CH1 __INIT(NULL);
__DEFINE DIAG		 *pdiag_CH1 __INIT(NULL);
__DEFINE N_VISPLC_V2 *pn_visplc_v2_CH1 __INIT(NULL);
__DEFINE SIN		 *psin_CH1 __INIT(NULL);
__DEFINE CNF_V2		 *pcnf_v2_CH1 __INIT(NULL);
__DEFINE ARETPLC_V4	 *paretplc_v2_CH1 __INIT(NULL);
__DEFINE N_DMAND_V3	 *pn_dmand_CH1 __INIT(NULL);


//Ch2
__DEFINE DATI *p_m_CH2 __INIT(NULL);
__DEFINE double *Aris_CH2 __INIT(NULL);
__DEFINE double *Acus_CH2 __INIT(NULL);
__DEFINE PCNCPLC_DATA p_dplc_v3_CH2 __INIT(NULL);

//strutture della navetta da inizializzare in main
__DEFINE PCKEY		 *ppckey_CH2 __INIT(NULL);
__DEFINE N_XOUT		 *pn_xout_CH2 __INIT(NULL);
__DEFINE N_XIN		 *pn_xin_CH2 __INIT(NULL);
__DEFINE N_AREC_V3	 *pn_arec_v2_CH2 __INIT(NULL);
__DEFINE N_ARED_V3	 *pn_ared_v2_CH2 __INIT(NULL);
__DEFINE N_SAREC	 *pn_sarec_CH2 __INIT(NULL);
__DEFINE N_KEY		 *pn_key_CH2 __INIT(NULL);
__DEFINE IO_V3		 *pio_v2_CH2 __INIT(NULL);
__DEFINE DIAG		 *pdiag_CH2 __INIT(NULL);
__DEFINE N_VISPLC_V2 *pn_visplc_v2_CH2 __INIT(NULL);
__DEFINE SIN		 *psin_CH2 __INIT(NULL);
__DEFINE CNF_V2		 *pcnf_v2_CH2 __INIT(NULL);
__DEFINE ARETPLC_V4	 *paretplc_v2_CH2 __INIT(NULL);
__DEFINE N_DMAND_V3	 *pn_dmand_CH2 __INIT(NULL);



//Ch3
__DEFINE DATI *p_m_CH3 __INIT(NULL);
__DEFINE double *Aris_CH3 __INIT(NULL);
__DEFINE double *Acus_CH3 __INIT(NULL);
__DEFINE PCNCPLC_DATA p_dplc_v3_CH3 __INIT(NULL);

//strutture della navetta da inizializzare in main
__DEFINE PCKEY		 *ppckey_CH3 __INIT(NULL);
__DEFINE N_XOUT		 *pn_xout_CH3 __INIT(NULL);
__DEFINE N_XIN		 *pn_xin_CH3 __INIT(NULL);
__DEFINE N_AREC_V3	 *pn_arec_v2_CH3 __INIT(NULL);
__DEFINE N_ARED_V3	 *pn_ared_v2_CH3 __INIT(NULL);
__DEFINE N_SAREC	 *pn_sarec_CH3 __INIT(NULL);
__DEFINE N_KEY		 *pn_key_CH3 __INIT(NULL);
__DEFINE IO_V3		 *pio_v2_CH3 __INIT(NULL);
__DEFINE DIAG		 *pdiag_CH3 __INIT(NULL);
__DEFINE N_VISPLC_V2 *pn_visplc_v2_CH3 __INIT(NULL);
__DEFINE SIN		 *psin_CH3 __INIT(NULL);
__DEFINE CNF_V2		 *pcnf_v2_CH3 __INIT(NULL);
__DEFINE ARETPLC_V4	 *paretplc_v2_CH3 __INIT(NULL);
__DEFINE N_DMAND_V3	 *pn_dmand_CH3 __INIT(NULL);


#pragma pack (pop)
