
// ********************************************************************************************************************************************/

#define MI_6W0_BL               PLC_INPUT_BYTE(5, 0, 0)    /*Byte LOW */
#define MI_6W0_BH               PLC_INPUT_BYTE(5, 0, 1)    /*Byte HIGH */

#define MI_6W1_BL               PLC_INPUT_BYTE(5, 1, 0)    /*Byte LOW */
#define MI_6W1_BH               PLC_INPUT_BYTE(5, 1, 1)    /*Byte HIGH */

#define MI_6W2_BL               PLC_INPUT_BYTE(5, 2, 0)    /*Byte LOW */
#define MI_6W2_BH               PLC_INPUT_BYTE(5, 2, 1)    /*Byte HGH */

#define MI_6W3_BL               PLC_INPUT_BYTE(5, 3, 0)    /*Byte LOW */
#define MI_6W3_BH               PLC_INPUT_BYTE(5, 3, 1)    /*Byte HGH */

#define MI_6W4_BL               PLC_INPUT_BYTE(5, 4, 0)    /*Byte LOW */
#define MI_6W4_BH               PLC_INPUT_BYTE(5, 4, 1)    /*Byte HGH */
             
#define MI_6W5_BL               PLC_INPUT_BYTE(5, 5, 0)    /*Byte LOW */
#define MI_6W5_BH               PLC_INPUT_BYTE(5, 5, 1)    /*Byte HGH */
             
#define MI_6W6_BL               PLC_INPUT_BYTE(5, 6, 0)    /*Byte LOW */
#define MI_6W6_BH               PLC_INPUT_BYTE(5, 6, 1)    /*Byte HGH */

#define MI_6W7_BL               PLC_INPUT_BYTE(5, 7, 0)    /*Byte LOW */
#define MI_6W7_BH               PLC_INPUT_BYTE(5, 7, 1)    /*Byte HIGH */

#define MI_6W8_BL               PLC_INPUT_BYTE(5, 8, 0)    /*Byte LOW */
#define MI_6W8_BH               PLC_INPUT_BYTE(5, 8, 1)    /*Byte HIGH */

#define MI_6W9_BL               PLC_INPUT_BYTE(5, 9, 0)    /*Byte LOW */
#define MI_6W9_BH               PLC_INPUT_BYTE(5, 9, 1)    /*Byte HIGH */

#define MI_6W10_BL              PLC_INPUT_BYTE(5, 10, 0)   /*Byte LOW */
#define MI_6W10_BH              PLC_INPUT_BYTE(5, 10, 1)   /*Byte HIGH */

#define MI_6W11_BL              PLC_INPUT_BYTE(5, 11, 0)    /*Byte LOW */
#define MI_6W11_BH              PLC_INPUT_BYTE(5, 11, 1)    /*Byte HIGH */

// ********************************************************************************************************************************************/

