[ALARM]
1=ALARMA EJE X - Anomalía accionamiento eje X
2=ALARMA EJE Y - Anomalía accionamiento eje Y
3=ALARMA EJE Z - Anomalía accionamiento eje Z
4=ALARMA EJE B - Anomalía accionamiento eje B
5=ALARMA EJE C - Anomalía accionamiento eje C
6=ALARMA EJE W - Anomalía accionamiento eje W
9=ALARMA GENERAL - No hay corriente en el eje accionamiento
15=ALARMA SOFTWARE - Allarme lettura scrittura contatori
19=ALARMA EJE MORDAZA M10 - Anomalía accionamiento eje mordaza M10
20=ALARMA EJE MORDAZA M11 - Anomalía accionamiento eje mordaza M11
21=ALARMA EJE MORDAZA M12 - Anomalía accionamiento eje mordaza M12
22=ALARMA EJE MORDAZA M13 - Anomalía accionamiento eje mordaza M13
23=ALARMA EJE MORDAZA M14 - Anomalía accionamiento eje mordaza M14
24=ALARMA EJE MORDAZA M15 - Anomalía accionamiento eje mordaza M15
32=ALARMA GENERAL - Anomalía en los dispositivos de alimentación
33=ALARMA GENERAL - Botón de emergencia presionado
34=ALARMA GENERAL - Dispositivos auxiliares no activados
35=ALARMA GENERAL - Presión aire insuficiente
36=ALARMA GENERAL - Temperatura armario no correcta
37=ALARMA GENERAL - Relés térmicos activados
39=ALARMA TRANSPORTADOR DE VIRUTAS - Relé térmico de transportador 
40=ALARMA ASPIRADOR - Relé térmico aspirador IZQ activado
42=ALARMA GENERAL - CNC en estado de alarma
43=ALARMA GENERAL - CNC1 en estado de alarma
44=ALARMA GENERAL - CNC2 en estado de alarma
46=ALARMA GENERAL - CNC0, CNC1, CNC2 non tutti in manuale
47=ALARMA GENERAL - CNC0, CNC1, CNC2 non tutti in automatico
48=ALARMA MANDRIL - Anomalía inverter mandril
49=ALARMA MANDRIL - Inverter mandril en sobrecarga
50=ALARMA MANDRIL - Mandril no en rotación
51=ALARMA MANDRIL - Velocidad de régimen no correcta
52=ALARMA MANDRIL - Time out desbloqueo herramienta
53=ALARMA MANDRIL - Time out bloqueo herramienta
54=ALARMA MANDRIL - Anomalía microinterruptor bloqueo herramienta
55=ALARMA MANDRIL - Herramienta no fijada correctamente
56=ALARMA MANDRIL - Herramienta desconocida en el mandril
57=ALLARME MANDRINO - Termico Centralina di Raffreddamento Mandrino scattato
58=ALARMA MANDRIL - Alarma regulador de flujo centralita de refrigeración del mandril
62=ALARMA HUSILLO - Vibraciones excesivas en el husillo
63=ALARMA HUSILLO - Exceso de temperatura en el husillo
64=ALARMA EJE - Eje X en extracarrera positivo
65=ALARMA EJE - Eje X en extracarrera negativo
66=ALARMA EJE - Eje Y en extracarrera positivo
67=ALARMA EJE - Eje Y en extracarrera negativo
68=ALARMA EJE - Eje Z en extracarrera positivo
69=ALARMA EJE - Eje Z en extracarrera negativo
70=ALARMA EJE - Eje B en extracarrera positivo
71=ALARMA EJE - Eje B en extracarrera negativo
72=ALARMA EJE - Eje C en extracarrera positivo
73=ALARMA EJE - Eje C en extracarrera negativo
74=ALARMA EJE - Eje P en extracarrera positivo
75=ALARMA EJE - Eje P en extracarrera negativo
76=ALARMA EJE - Eje H en extracarrera positivo
77=ALARMA EJE - Eje H en extracarrera negativo
78=ALARMA EJE - Eje W en extracarrera positivo
79=ALARMA EJE - Eje W en extracarrera negativo
80=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 1
81=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 1
82=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 2
83=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 2
84=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 3
85=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 3
86=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 4
87=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 4
88=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 5
89=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 5
90=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 6
91=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 6
92=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 7
93=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 7
94=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 8
95=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 8
96=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 9
97=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 9
98=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 10
99=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 10
100=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 11
101=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 11
102=ALARMA CAMBIO HERRAMIENTAS - Imposible depositar la herramienta 12
103=ALARMA CAMBIO HERRAMIENTAS - Imposible sacar la herramienta 12
104=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non disinserito
105=ALARMA ALMACEN HERRAMIENTAS - Ciclo empezado con mandril en choque potencial con almacen
106=ALLARME MAGAZZINO UTENSILI - Gancio magazzino utensile non fuori ingombro
107=ALARMA MORDAZAS - Alta presión activa sin mando
108=ALARMA EJES - Posible colisión entre la herramienta y los protectores delanteros
115=ALARMA MORDAZAS - La mordaza 10 no está en posición correcta
116=ALARMA MORDAZAS - La mordaza 11 no está en posición correcta
117=ALARMA MORDAZAS - La mordaza 12 no está en posición correcta
118=ALARMA MORDAZAS - La mordaza 13 no está en posición correcta
119=ALARMA MORDAZAS - La mordaza 14 no está en posición correcta
120=ALARMA MORDAZAS - La mordaza 15 no está en posición correcta
124=ALARMA MORDAZAS - Cálculo mordazas erróneo
125=ALARMA MORDAZAS - Error pos. Mordazas desde PC: valores fuera de campo
136=ALARMA MORDAZAS - Alimentatore morse motorizzate non OK
138=ALLARME BATTUTA DI PRECISIONE - Battuta non inserita
139=ALLARME BATTUTA DI PRECISIONE - Battuta non disinserita
140=ALLARME BATTUTA DI PRECISIONE - Errore posizione a riposo della battuta
141=ALLARME BATTUTA DI PRECISIONE - Errore indice di tastatura
142=ALLARME BATTUTA DI PRECISIONE - Pezzo non trovato
143=ALLARME DI POSIZIONAMENTO - Pezzo appoggiato male alla battuta di riferimento
154=ALLARME BATTUTE - Battuta DX4 non in posizione X4R
155=ALLARME BATTUTE - Disfunzione Finecorsa Battuta DX4
156=ALLARME BATTUTE - Battuta SX1 non in posizione X1L
157=ALLARME BATTUTE - Battuta DX4 non in posizione X3R
158=ALLARME BATTUTE - Battuta DX4 non in posizione X2R
159=ALLARME BATTUTE - Battuta DX4 non in posizione X1R
160=ALARMA TOPES - Tope IZQ 1 no alto
161=ALARMA TOPES - Tope IZQ 1 no bajo
166=ALARMA TOPES  Tope DCH 4 no alto
167=ALARMA TOPES - Tope DCH 4 no bajo
176=ALARMA MESAS - Mesa no adelante: controlar el detector
177=ALARMA MESAS - Mesa no adelante: controlar el detector
178=ALARMA MESAS - Mesa no atrás: controlar el detector
179=ALARMA MESAS - Mesa no atrás: controlar la EV
180=ALARMA MESAS - Anomalía Microinterruptor Mesa
198=ALARMA LUBRICA - Nivel bajo sistema Lubrica normal
199=ALLARME LUBRICA - Livello lubrica normale alto
200=ALARMA PALPADOR MARPOSS - Palpador ya en tope al inicio del cabezal
201=ALARMA PALPADOR MARPOSS - Pieza no detectada por el palpador
202=ALARMA PALPADOR MARPOSS - Error indice palpador
203=ALARMA PALPADOR MARPOSS - Palpador marposs en error
204=ALARMA PALPADOR MARPOSS - Bateria descargada palpador marposs
205=ALARMA PALPADOR MARPOSS - Palpador aun en tope despues de final de palpado
206=ALARMA PALPADOR MARPOSS - Correzioni troppo grandi: verificare il tastatore
212=ALLARME INGRASSAGGIO GUIDE - Livello grasso basso
213=ALLARME INGRASSAGGIO GUIDE - Anomalia pompa/elettrovalvola
214=ALLARME INGRASSAGGIO GUIDE - Mancata esecuzione per troppe ore lavorative
215=ALLARME INGRASSAGGIO GUIDE - Mancata commutazione sensore sulla singola pompata 
224=ALARMA SOFTWARE - Error en la apertura/cierre archivo:  Path_conf.Txt
225=ALARMA SOFTWARE - Error en la apertura del archivo:  config.par
226=ALARMA SOFTWARE - Error en la apertura del archivo:  tools.txt
227=ALARMA SOFTWARE - Error en la apertura del archivo:  heads.txt
228=ALARMA SOFTWARE - Error en llamada herramienta
229=ALARMA SOFTWARE - Error en el cierre del archivo: config.par/tools.txt/heads.txt
230=ALARMA SOFTWARE - Error en la lectura del archivo
231=ALARMA SOFTWARE - Error en la apertura del archivo:  variable.txt
232=ALARMA SOFTWARE - Error en el cierre del archivo: variable.txt
233=ALARMA SOFTWARE - Alarma falta driver
234=ALARMA SOFTWARE - Configuración de máquina errónea
235=ALARMA SOFTWARE - Valor fuera de los límites durante los controles Routine Iso Cnc
236=ALARMA SOFTWARE - Tabla herramientas no cargada (ejecute M209)
237=ALARMA SOFTWARE - Alarma movimiento ejes X - Y - Z
243=ALARMA MORDAZAS - mordaza 10 no en posición
244=ALARMA MORDAZAS - mordaza 11 no en posición
245=ALARMA MORDAZAS - mordaza 12 no en posición
246=ALARMA MORDAZAS - mordaza 13 no en posición
247=ALARMA MORDAZAS - mordaza 14 no en posición
248=ALARMA MORDAZAS - mordaza 15 no en posición
252=ALARMA MORDAZAS - Microinterruptor mordaza perdido durante posicionamiento
253=ALARMA MORDAZAS - Microinterruptor mordaza Eje X no encontrado en control de posición
256=ALLARME GENERALE - Errore caricamento ISOMG in memoria
257=ALLARME GENERALE - Timeout caricamento ISOMG in memoria
260=ALARMA CAN OPEN - Comunicación CanOpen en anomalía
270=ALLARME RIPARI - Riparo laterale o tunnel SX non chiuso
271=ALLARME RIPARI - Riparo laterale o tunnel DX non chiuso
272=ALARMA PROTECCIONES - Time out protección delantera no cerrada: controlar el sensor
273=ALARMA PROTECCIONES - Time out protección delantera no cerrada: controlar la EV
274=ALARMA PROTECCIONES - Time out protección delantera no abierta: controlar el sensor
275=ALARMA PROTECCIONES - Time out protección delantera no abierta: controlar la EV.
276=ALARMA PROTECCIONES - Anomalía microinterruptor protección delantera
282=ALARMA PROTECCIONES - Protección trasera IZQ no cerrada
283=ALARMA PROTECCIONES - Protección trasera DCH no cerrada
286=ALARMA PROTECCIONES - Centralita de seguridad no activa con protección cerrada
298=ALLARME RIPARI - Bordo sensibile ripari intervenuto
320=ALARMA ARRASTRADOR DE MORDAZAS - Arrastr.Mordazas Eje X no activado: controlar el detector
321=ALARMA ARRASTRADOR DE MORDAZAS - Arrastr.Mordazas Eje X no activado: controlar la EV
322=ALARMA ARRASTRADOR DE MORDAZAS - Arrastr.Mordazas Eje X no desactivado: controlar el detector
323=ALARMA ARRASTRADOR DE MORDAZAS - Arrastr.Mordazas Eje X no desactivado: controlar la EV
324=ALARMA ARRASTRADOR DE MORDAZAS - Anomalía Microinterruptor Arrastr. Mordazas Eje X
342=ALLARME RILEVAMENTO MORSE - Time out inserzione rilevamento morse
343=ALLARME RILEVAMENTO MORSE - Time out disinserzione rilevamento morse
371=ALLARME MORSE - Alta pressione non attiva su morsa 10
372=ALLARME MORSE - Alta pressione non attiva su morsa 11
373=ALLARME MORSE - Alta pressione non attiva su morsa 12
374=ALLARME MORSE - Alta pressione non attiva su morsa 13
375=ALLARME MORSE - Alta pressione non attiva su morsa 14
376=ALLARME MORSE - Alta pressione non attiva su morsa 15
384=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla il sensore
385=ALLARME RIPARI - Time Out Visiera bassa non aperta (avanzamento) : controlla la EV
386=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla il sensore
387=ALLARME RIPARI - Time Out Visiera bassa non chiusa (arretramento) : controlla la EV
388=ALLARME RIPARI - Disfunzione finecorsa visiera bassa
394=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla il sensore
395=ALLARME RIPARI - Time Out Visiera alta non aperta (discesa) : controlla la EV
396=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla il sensore
397=ALLARME RIPARI - Time Out Visiera alta non chiusa (salita) : controlla la EV
402=ALLARME UTENSILI - Utensile T1 rotto
403=ALLARME UTENSILI - Utensile T2 rotto
404=ALLARME UTENSILI - Utensile T3 rotto
405=ALLARME UTENSILI - Utensile T4 rotto
406=ALLARME UTENSILI - Utensile T5 rotto
407=ALLARME UTENSILI - Utensile T6 rotto
408=ALLARME UTENSILI - Utensile T7 rotto
409=ALLARME UTENSILI - Utensile T8 rotto
410=ALLARME UTENSILI - Utensile T9 rotto
411=ALLARME UTENSILI - Utensile T10 rotto
412=ALLARME UTENSILI - Utensile T11 rotto
413=ALLARME UTENSILI - Utensile T12 rotto
414=ALLARME UTENSILI - Drill not alive
416=ALLARME GANTRY - Morse non agganciate in gantry
417=ALLARME GANTRY - Morse non sganciate in gantry
418=ALLARME ASSI MORSE - Posizioni assi morse non congruenti (posizioni encoder perse)
419=ALARMA CAMBIO DE HERRAMIENTAS - Incongruencia entre herramienta teorica presente y sensor de presencia her.
420=ALARMA DE VERIFICACION DE HERRAMIENTA - Herramienta rota
421=ALARMA DE VERIFICACION DE HERRAMIENTA - El dispositivo de verificacion de integridad de la herramienta no funciona
438=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa positivo
439=ALLARME ASSE MORSA - Asse Morsa M10 in extracorsa negativo
440=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa positivo
441=ALLARME ASSE MORSA - Asse Morsa M11 in extracorsa negativo
442=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa positivo
443=ALLARME ASSE MORSA - Asse Morsa M12 in extracorsa negativo
444=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa positivo
445=ALLARME ASSE MORSA - Asse Morsa M13 in extracorsa negativo
446=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa positivo
447=ALLARME ASSE MORSA - Asse Morsa M14 in extracorsa negativo
448=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa positivo
449=ALLARME ASSE MORSA - Asse Morsa M15 in extracorsa negativo
475=ALLARME CONFIGURAZIONE - Errore inizializzazione variabili PLC
476=ALLARME CONFIGURAZIONE - Errore lettura confmac
477=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (MGPilot)
478=ALLARME CONFIGURAZIONE - Errore caricamento funzioni manuali (REM_CTRL)
480=ALLARME ASSE X - Livello Batteria encoder basso
481=ALLARME ASSE Y - Livello Batteria encoder basso
482=ALLARME ASSE Z - Livello Batteria encoder basso
483=ALLARME ASSE A - Livello Batteria encoder basso
484=ALLARME ASSE W - Livello Batteria encoder basso
487=ALLARME ASSE X - Livello Batteria encoder basso e posizione assoluta persa
488=ALLARME ASSE Y - Livello Batteria encoder basso e posizione assoluta persa
489=ALLARME ASSE Z - Livello Batteria encoder basso e posizione assoluta persa
490=ALLARME ASSE A - Livello Batteria encoder basso e posizione assoluta persa
491=ALLARME ASSE W - Livello Batteria encoder basso e posizione assoluta persa
496=ALLARME ASSE X - Overflow sui giri massimi del multiturn dell'encoder assoluto
497=ALLARME ASSE Y - Overflow sui giri massimi del multiturn dell'encoder assoluto
498=ALLARME ASSE Z - Overflow sui giri massimi del multiturn dell'encoder assoluto
499=ALLARME ASSE A - Overflow sui giri massimi del multiturn dell'encoder assoluto
500=ALLARME ASSE W - Overflow sui giri massimi del multiturn dell'encoder assoluto
503=ALLARME ASSE X - Posizione assoluta encoder non inizializzata
504=ALLARME ASSE Y - Posizione assoluta encoder non inizializzata
505=ALLARME ASSE Z - Posizione assoluta encoder non inizializzata
506=ALLARME ASSE A - Posizione assoluta encoder non inizializzata
507=ALLARME ASSE W - Posizione assoluta encoder non inizializzata
512=ALLARME ASSE X - Funzione di reset encoder assoluto non riuscita
513=ALLARME ASSE Y - Funzione di reset encoder assoluto non riuscita
514=ALLARME ASSE Z - Funzione di reset encoder assoluto non riuscita
515=ALLARME ASSE A - Funzione di reset encoder assoluto non riuscita
516=ALLARME ASSE W - Funzione di reset encoder assoluto non riuscita
519=ALLARME ASSE X - La tensione DC del circuito principale è più bassa del valore standard
520=ALLARME ASSE Y - La tensione DC del circuito principale è più bassa del valore standard
521=ALLARME ASSE Z - La tensione DC del circuito principale è più bassa del valore standard
522=ALLARME ASSE A - La tensione DC del circuito principale è più bassa del valore standard
523=ALLARME ASSE W - La tensione DC del circuito principale è più bassa del valore standard
528=ALLARME ASSE X - Mancanza di una fase in ingresso
529=ALLARME ASSE Y - Mancanza di una fase in ingresso
530=ALLARME ASSE Z - Mancanza di una fase in ingresso
531=ALLARME ASSE A - Mancanza di una fase in ingresso
532=ALLARME ASSE W - Mancanza di una fase in ingresso
535=ALLARME ASSE X - La velocità del motore è in overshoot rispetto al valore massimo di targa
536=ALLARME ASSE Y - La velocità del motore è in overshoot rispetto al valore massimo di targa
537=ALLARME ASSE Z - La velocità del motore è in overshoot rispetto al valore massimo di targa
538=ALLARME ASSE A - La velocità del motore è in overshoot rispetto al valore massimo di targa
539=ALLARME ASSE W - La velocità del motore è in overshoot rispetto al valore massimo di targa
544=ALLARME PLC IEC - PLC IEC timeout di not alive
545=ALLARME PLC IEC - Errore di comunicazione COM con inverter 0
560=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse X
561=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Y
562=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse Z
563=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse A
564=ALLARME PLC IEC - Errore di comunicazione COM con azionamento asse W

[MSG]
1=MENSAJE OPERADOR - Referencia ejes no efectuada
2=MENSAJE OPERADOR - máquina en estado de hold
3=MENSAJE OPERADOR - herramienta desconocida en el mandril
4=MENSAJE OPERADOR - Potenciómetro a cero en ciclo automático
5=MENSAJE OPERADOR - Máquina en HOLD debido a la condición del almacén
6=MENSAJE OPERADOR - Máquina en HOLD por Mordazas Zona IZQ
7=MENSAJE OPERADOR - Máquina en HOLD por Mordazas Zona DCH
8=MENSAJE OPERADOR - Máquina en HOLD por Mandril 
9=MENSAJE OPERADOR - Máquina en HOLD por Protecciones
10=MENSAJE OPERADOR - Magazzino in potenziale collisione col carter laterale SX della macchina
11=MENSAJE OPERADOR - Choque potencial del mandril con almacen
12=MENSAJE OPERADOR - bloqueo ejecuciones FATM activo
13=MENSAJE OPERADOR - Hold apertura / chiusura ripari anteriori da posizione assi Y, B, C
14=MENSAJE OPERADOR - atención: posible corto en entradas de accionamiento no mantenido
15=MENSAJE OPERADOR - Potenziale collisione fra utensile e riparo anteriore
16=MENSAJE OPERADOR - Desb. herr. directo sólo con protecciones bajas
25=MENSAJE OPERADOR - Engrase automático desactivado
27=MENSAJE OPERADOR - Assenza uscite pericolose con centralina di sicurezza ok
30=MENSAJE OPERADOR - Bridge password initialization done, restart
31=MENSAJE OPERADOR - Errore scrittura file contatori
77=MENSAJE OPERADOR - Errore caricamento funzioni manuali (MGPilot)
78=MENSAJE OPERADOR - Errore caricamento funzioni manuali (REM_CTRL)
80=MESSAGGIO OPERATORE - Motore asse X in preallarme da sovraccarico
81=MESSAGGIO OPERATORE - Motore asse Y in preallarme da sovraccarico
82=MESSAGGIO OPERATORE - Motore asse Z in preallarme da sovraccarico
83=MESSAGGIO OPERATORE - Motore asse A in preallarme da sovraccarico
84=MESSAGGIO OPERATORE - Motore asse W in preallarme da sovraccarico
88=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso e posizione assoluta persa
89=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso e posizione assoluta persa
90=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso e posizione assoluta persa
91=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso e posizione assoluta persa
92=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso e posizione assoluta persa
96=MESSAGGIO OPERATORE - Livello Batteria encoder asse X basso
97=MESSAGGIO OPERATORE - Livello Batteria encoder asse Y basso
98=MESSAGGIO OPERATORE - Livello Batteria encoder asse Z basso
99=MESSAGGIO OPERATORE - Livello Batteria encoder asse A basso
100=MESSAGGIO OPERATORE - Livello Batteria encoder asse W basso
104=MESSAGGIO OPERATORE - Posizione assoluta encoder asse X non inizializzata
105=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Y non inizializzata
106=MESSAGGIO OPERATORE - Posizione assoluta encoder asse Z non inizializzata
107=MESSAGGIO OPERATORE - Posizione assoluta encoder asse A non inizializzata
108=MESSAGGIO OPERATORE - Posizione assoluta encoder asse W non inizializzata
112=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse X
113=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Y
114=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse Z
115=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse A
116=MESSAGGIO OPERATORE - Overflow sui giri massimi del multiturn dell'encoder assoluto asse W
