A          B ACTIVAR 
A ABRIR    B CERRAR 
A JOG -    B JOG + 
A DEPOSITO B RECOGID 
A BAJADA   B SUBIDA 
A ATRAS   B ADELANTE 
A ORARIO B ANTIORAR. 
A FINAL   B COMIENZO 
A BLOQUE B DESBLOQUE 
A SX       B DX 
