@ECHO OFF

REM COPIA DI plcm.dll E DESCRIZIONI I/O SULLA MACCHINA CONNESSA VIA RETE  (in "X:\plc\plc\")

REM ///////////////////////////////////////////////////////////////////////////////////////////////

REM copia in macchina:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreSimuPC\plcm.dll"   "X:\plc\plc\"
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreSimuPC\plcm.dll"   "Y:\_PLC\"


REM copia su chiave USB:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreSimuPC\plcm.dll"   "G:\_______XXX\"

REM copia su C:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreSimuPC\plcm.dll"   "C:\plc\plc\"

REM PAUSE
