@ECHO OFF

REM COPIA E RINOMINA PLC

rem C:
rem CD "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\74EttoreSimuCN\"
rem copy plcm74.plc  plcm.plc


REM COPIA DI PLCM.PLC E DESCRIZIONI I/O SULLA MACCHINA CONNESSA VIA RETE  (in "X:\plc\plc\")

REM ///////////////////////////////////////////////////////////////////////////////////////////////

REM copia sul SIMULATORE:
rem copy "plcm.plc"   "V:\plc\plc\"
rem copy "plcm.plc"   "W:\_PLC\"


REM copia su chiave USB:
REM copy "plcm.plc"   "G:\_______XXX\"

REM PAUSE
