@ECHO OFF

rem comando:	"$(SolutionDir)\BAT\EttoreRelease__PLC.BAT"

REM COPIA DI PLCM.PLC E DESCRIZIONI I/O SULLA MACCHINA CONNESSA VIA RETE  (in "X:\plc\plc\")

REM ///////////////////////////////////////////////////////////////////////////////////////////////

REM copia in macchina:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreRelease\plcm.plc"   "X:\plc\plc\"
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreRelease\plcm.plc"   "Y:\_PLC\"


REM copia su chiave USB:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreRelease\plcm.plc"   "G:\_______XXX\"

REM copia da chiave USB in macchina:
rem copy "E:\Comet_S4\PROGETTO\Comet_S4\PLC\plcm\EttoreRelease\plcm.plc"   "C:\plc\plc\"
rem copy "E:\Comet_S4\PROGETTO\Comet_S4\PLC\plcm\EttoreRelease\plcm.plc"   "D:\_PLC\"
rem 
rem PAUSE
