@ECHO OFF

rem comando:	"$(SolutionDir)\BAT\EttoreSimuCN__PLC.BAT"

REM COPIA DI PLCM.PLC E DESCRIZIONI I/O SULLA MACCHINA CONNESSA VIA RETE  (in "X:\plc\plc\")

REM ///////////////////////////////////////////////////////////////////////////////////////////////

REM copia in macchina:
rem copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreSimuCN\plcm.plc"   "X:\plc\plc\"
rem copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreSimuCN\plcm.plc"   "Y:\_PLC\"


REM copia su chiave USB:
REM copy "C:\Prodotti\Progetti Cnc 7_0\Comet_S4\PLC\plcm\EttoreSimuCN\plcm.plc"   "G:\_______XXX\"

REM PAUSE
